package com.imum.cpms.model.transactions.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 18 16:50:06 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AuctionEvaluationVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AuctionEvaluationVOImpl() {
    }
}
