package com.imum.cpms.model.transactions.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 19 15:20:08 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AuctionClosingVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AuctionClosingVOImpl() {
    }
}
