package com.imum.cpms.model.transactions.vo;

import com.imum.cpms.model.transactions.eo.DepositAckDetailsEOImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 13 14:36:47 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepositAckDetailsUVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        DepositAckSeq {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getDepositAckSeq();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setDepositAckSeq((BigDecimal)value);
            }
        }
        ,
        BankAccinfoSeq {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getBankAccinfoSeq();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setBankAccinfoSeq((BigDecimal)value);
            }
        }
        ,
        DepositeDate {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getDepositeDate();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setDepositeDate((Timestamp)value);
            }
        }
        ,
        DepositorName {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getDepositorName();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setDepositorName((String)value);
            }
        }
        ,
        DepositeSlipAmt {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getDepositeSlipAmt();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setDepositeSlipAmt((BigDecimal)value);
            }
        }
        ,
        DepositeSlipAckDate {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getDepositeSlipAckDate();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setDepositeSlipAckDate((Timestamp)value);
            }
        }
        ,
        Depositslipnum {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getDepositslipnum();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setDepositslipnum((String)value);
            }
        }
        ,
        CashSource {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getCashSource();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setCashSource((String)value);
            }
        }
        ,
        SaleTrnDate {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getSaleTrnDate();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setSaleTrnDate((Timestamp)value);
            }
        }
        ,
        Ackslipnum {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getAckslipnum();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setAckslipnum((String)value);
            }
        }
        ,
        ExpectedAmt {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getExpectedAmt();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setExpectedAmt((BigDecimal)value);
            }
        }
        ,
        Discrepancyflag {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getDiscrepancyflag();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setDiscrepancyflag((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setCreatedDate((Timestamp)value);
            }
        }
        ,
        Updatedby {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getUpdatedby();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setUpdatedby((String)value);
            }
        }
        ,
        updateddate {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getupdateddate();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setupdateddate((Timestamp)value);
            }
        }
        ,
        LOCATIONID {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getLOCATIONID();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setLOCATIONID((Integer)value);
            }
        }
        ,
        CashSrcDesc {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getCashSrcDesc();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setCashSrcDesc((String)value);
            }
        }
        ,
        BankAccInfoRVO1 {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getBankAccInfoRVO1();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LocationTypeLVO1 {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getLocationTypeLVO1();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DepAckDtlLocLOVVO1 {
            public Object get(DepositAckDetailsUVORowImpl obj) {
                return obj.getDepAckDtlLocLOVVO1();
            }

            public void put(DepositAckDetailsUVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(DepositAckDetailsUVORowImpl object);

        public abstract void put(DepositAckDetailsUVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DEPOSITACKSEQ = AttributesEnum.DepositAckSeq.index();
    public static final int BANKACCINFOSEQ = AttributesEnum.BankAccinfoSeq.index();
    public static final int DEPOSITEDATE = AttributesEnum.DepositeDate.index();
    public static final int DEPOSITORNAME = AttributesEnum.DepositorName.index();
    public static final int DEPOSITESLIPAMT = AttributesEnum.DepositeSlipAmt.index();
    public static final int DEPOSITESLIPACKDATE = AttributesEnum.DepositeSlipAckDate.index();
    public static final int DEPOSITSLIPNUM = AttributesEnum.Depositslipnum.index();
    public static final int CASHSOURCE = AttributesEnum.CashSource.index();
    public static final int SALETRNDATE = AttributesEnum.SaleTrnDate.index();
    public static final int ACKSLIPNUM = AttributesEnum.Ackslipnum.index();
    public static final int EXPECTEDAMT = AttributesEnum.ExpectedAmt.index();
    public static final int DISCREPANCYFLAG = AttributesEnum.Discrepancyflag.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.Updatedby.index();
    public static final int UPDATEDDATE = AttributesEnum.updateddate.index();
    public static final int LOCATIONID = AttributesEnum.LOCATIONID.index();
    public static final int CASHSRCDESC = AttributesEnum.CashSrcDesc.index();
    public static final int BANKACCINFORVO1 = AttributesEnum.BankAccInfoRVO1.index();
    public static final int LOCATIONTYPELVO1 = AttributesEnum.LocationTypeLVO1.index();
    public static final int DEPACKDTLLOCLOVVO1 = AttributesEnum.DepAckDtlLocLOVVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DepositAckDetailsUVORowImpl() {
    }

    /**
     * Gets DepositAckDetailsEO entity object.
     * @return the DepositAckDetailsEO
     */
    public DepositAckDetailsEOImpl getDepositAckDetailsEO() {
        return (DepositAckDetailsEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for Deposit_Ack_Seq using the alias name DepositAckSeq.
     * @return the Deposit_Ack_Seq
     */
    public BigDecimal getDepositAckSeq() {
        return (BigDecimal) getAttributeInternal(DEPOSITACKSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for Deposit_Ack_Seq using the alias name DepositAckSeq.
     * @param value value to set the Deposit_Ack_Seq
     */
    public void setDepositAckSeq(BigDecimal value) {
        setAttributeInternal(DEPOSITACKSEQ, value);
    }

    /**
     * Gets the attribute value for Bank_Acc_info_Seq using the alias name BankAccinfoSeq.
     * @return the Bank_Acc_info_Seq
     */
    public BigDecimal getBankAccinfoSeq() {
        return (BigDecimal) getAttributeInternal(BANKACCINFOSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for Bank_Acc_info_Seq using the alias name BankAccinfoSeq.
     * @param value value to set the Bank_Acc_info_Seq
     */
    public void setBankAccinfoSeq(BigDecimal value) {
        setAttributeInternal(BANKACCINFOSEQ, value);
    }

    /**
     * Gets the attribute value for Deposite_Date using the alias name DepositeDate.
     * @return the Deposite_Date
     */
    public Timestamp getDepositeDate() {
        return (Timestamp) getAttributeInternal(DEPOSITEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for Deposite_Date using the alias name DepositeDate.
     * @param value value to set the Deposite_Date
     */
    public void setDepositeDate(Timestamp value) {
        setAttributeInternal(DEPOSITEDATE, value);
    }

    /**
     * Gets the attribute value for Depositor_Name using the alias name DepositorName.
     * @return the Depositor_Name
     */
    public String getDepositorName() {
        return (String) getAttributeInternal(DEPOSITORNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for Depositor_Name using the alias name DepositorName.
     * @param value value to set the Depositor_Name
     */
    public void setDepositorName(String value) {
        setAttributeInternal(DEPOSITORNAME, value);
    }

    /**
     * Gets the attribute value for Deposite_Slip_Amt using the alias name DepositeSlipAmt.
     * @return the Deposite_Slip_Amt
     */
    public BigDecimal getDepositeSlipAmt() {
        return (BigDecimal) getAttributeInternal(DEPOSITESLIPAMT);
    }

    /**
     * Sets <code>value</code> as attribute value for Deposite_Slip_Amt using the alias name DepositeSlipAmt.
     * @param value value to set the Deposite_Slip_Amt
     */
    public void setDepositeSlipAmt(BigDecimal value) {
        setAttributeInternal(DEPOSITESLIPAMT, value);
    }

    /**
     * Gets the attribute value for Deposite_Slip_Ack_Date using the alias name DepositeSlipAckDate.
     * @return the Deposite_Slip_Ack_Date
     */
    public Timestamp getDepositeSlipAckDate() {
        return (Timestamp) getAttributeInternal(DEPOSITESLIPACKDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for Deposite_Slip_Ack_Date using the alias name DepositeSlipAckDate.
     * @param value value to set the Deposite_Slip_Ack_Date
     */
    public void setDepositeSlipAckDate(Timestamp value) {
        setAttributeInternal(DEPOSITESLIPACKDATE, value);
    }

    /**
     * Gets the attribute value for Deposit_slip_num using the alias name Depositslipnum.
     * @return the Deposit_slip_num
     */
    public String getDepositslipnum() {
        return (String) getAttributeInternal(DEPOSITSLIPNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for Deposit_slip_num using the alias name Depositslipnum.
     * @param value value to set the Deposit_slip_num
     */
    public void setDepositslipnum(String value) {
        setAttributeInternal(DEPOSITSLIPNUM, value);
    }

    /**
     * Gets the attribute value for Cash_Source using the alias name CashSource.
     * @return the Cash_Source
     */
    public String getCashSource() {
        return (String) getAttributeInternal(CASHSOURCE);
    }

    /**
     * Sets <code>value</code> as attribute value for Cash_Source using the alias name CashSource.
     * @param value value to set the Cash_Source
     */
    public void setCashSource(String value) {
        setAttributeInternal(CASHSOURCE, value);
    }

    /**
     * Gets the attribute value for Sale_Trn_Date using the alias name SaleTrnDate.
     * @return the Sale_Trn_Date
     */
    public Timestamp getSaleTrnDate() {
        return (Timestamp) getAttributeInternal(SALETRNDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for Sale_Trn_Date using the alias name SaleTrnDate.
     * @param value value to set the Sale_Trn_Date
     */
    public void setSaleTrnDate(Timestamp value) {
        setAttributeInternal(SALETRNDATE, value);
    }

    /**
     * Gets the attribute value for Ack_slip_num using the alias name Ackslipnum.
     * @return the Ack_slip_num
     */
    public String getAckslipnum() {
        return (String) getAttributeInternal(ACKSLIPNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for Ack_slip_num using the alias name Ackslipnum.
     * @param value value to set the Ack_slip_num
     */
    public void setAckslipnum(String value) {
        setAttributeInternal(ACKSLIPNUM, value);
    }

    /**
     * Gets the attribute value for Expected_Amt using the alias name ExpectedAmt.
     * @return the Expected_Amt
     */
    public BigDecimal getExpectedAmt() {
        return (BigDecimal) getAttributeInternal(EXPECTEDAMT);
    }

    /**
     * Sets <code>value</code> as attribute value for Expected_Amt using the alias name ExpectedAmt.
     * @param value value to set the Expected_Amt
     */
    public void setExpectedAmt(BigDecimal value) {
        setAttributeInternal(EXPECTEDAMT, value);
    }

    /**
     * Gets the attribute value for Discrepancy_flag using the alias name Discrepancyflag.
     * @return the Discrepancy_flag
     */
    public String getDiscrepancyflag() {
        return (String) getAttributeInternal(DISCREPANCYFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for Discrepancy_flag using the alias name Discrepancyflag.
     * @param value value to set the Discrepancy_flag
     */
    public void setDiscrepancyflag(String value) {
        setAttributeInternal(DISCREPANCYFLAG, value);
    }

    /**
     * Gets the attribute value for Created_By using the alias name CreatedBy.
     * @return the Created_By
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for Created_By using the alias name CreatedBy.
     * @param value value to set the Created_By
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Created_Date using the alias name CreatedDate.
     * @return the Created_Date
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for Created_Date using the alias name CreatedDate.
     * @param value value to set the Created_Date
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Updated_by using the alias name Updatedby.
     * @return the Updated_by
     */
    public String getUpdatedby() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for Updated_by using the alias name Updatedby.
     * @param value value to set the Updated_by
     */
    public void setUpdatedby(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for updated_date using the alias name updateddate.
     * @return the updated_date
     */
    public Timestamp getupdateddate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for updated_date using the alias name updateddate.
     * @param value value to set the updated_date
     */
    public void setupdateddate(Timestamp value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for LOCATION_ID using the alias name LOCATIONID.
     * @return the LOCATION_ID
     */
    public Integer getLOCATIONID() {
        return (Integer) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATION_ID using the alias name LOCATIONID.
     * @param value value to set the LOCATION_ID
     */
    public void setLOCATIONID(Integer value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CashSrcDesc.
     * @return the CashSrcDesc
     */
    public String getCashSrcDesc() {
        return (String) getAttributeInternal(CASHSRCDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CashSrcDesc.
     * @param value value to set the  CashSrcDesc
     */
    public void setCashSrcDesc(String value) {
        setAttributeInternal(CASHSRCDESC, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BankAccInfoRVO1.
     */
    public RowSet getBankAccInfoRVO1() {
        return (RowSet)getAttributeInternal(BANKACCINFORVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LocationTypeLVO1.
     */
    public RowSet getLocationTypeLVO1() {
        return (RowSet)getAttributeInternal(LOCATIONTYPELVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DepAckDtlLocLOVVO1.
     */
    public RowSet getDepAckDtlLocLOVVO1() {
        return (RowSet)getAttributeInternal(DEPACKDTLLOCLOVVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
