package com.imum.cpms.model.transactions.vo;

import com.imum.cpms.model.transactions.eo.PVTDiscCnclDetailEOImpl;
import com.imum.cpms.model.transactions.eo.PVTDiscCnclHeaderEOImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jun 13 11:45:58 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class discountsearchVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PVTNum {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getPVTNum();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setPVTNum((String)value);
            }
        }
        ,
        CustFirstName {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getCustFirstName();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setCustFirstName((String)value);
            }
        }
        ,
        CustEmailID {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getCustEmailID();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setCustEmailID((String)value);
            }
        }
        ,
        CustLastName {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getCustLastName();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setCustLastName((String)value);
            }
        }
        ,
        CustMobilenum {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getCustMobilenum();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setCustMobilenum((BigDecimal)value);
            }
        }
        ,
        zonecode {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getzonecode();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setzonecode((String)value);
            }
        }
        ,
        SectorCode {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getSectorCode();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setSectorCode((String)value);
            }
        }
        ,
        PVTStatusID {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getPVTStatusID();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setPVTStatusID((Integer)value);
            }
        }
        ,
        PVTSTAGEID {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getPVTSTAGEID();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setPVTSTAGEID((Integer)value);
            }
        }
        ,
        PVTHDRSEQ {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getPVTHDRSEQ();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setPVTHDRSEQ((BigDecimal)value);
            }
        }
        ,
        Contracode {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getContracode();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setContracode((Integer)value);
            }
        }
        ,
        PVTAMTPAYABLE {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getPVTAMTPAYABLE();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setPVTAMTPAYABLE((BigDecimal)value);
            }
        }
        ,
        ApproverRemarks {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getApproverRemarks();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setApproverRemarks((String)value);
            }
        }
        ,
        DISCPROMONAME {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getDISCPROMONAME();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setDISCPROMONAME((String)value);
            }
        }
        ,
        DISCCNCLTYPE {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getDISCCNCLTYPE();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setDISCCNCLTYPE((String)value);
            }
        }
        ,
        DISCPROMOCODE {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getDISCPROMOCODE();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setDISCPROMOCODE((String)value);
            }
        }
        ,
        DISCCNCLhdrSeq {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getDISCCNCLhdrSeq();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setDISCCNCLhdrSeq((BigDecimal)value);
            }
        }
        ,
        DISCCNCLSTATUS {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getDISCCNCLSTATUS();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setDISCCNCLSTATUS((Integer)value);
            }
        }
        ,
        PromoeffectivedateTo {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getPromoeffectivedateTo();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setPromoeffectivedateTo((Timestamp)value);
            }
        }
        ,
        Promoeffectivedatefrom {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getPromoeffectivedatefrom();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setPromoeffectivedatefrom((Timestamp)value);
            }
        }
        ,
        DISCCNCLhdrSeq1 {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getDISCCNCLhdrSeq1();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setDISCCNCLhdrSeq1((BigDecimal)value);
            }
        }
        ,
        DISCCNCLDtlSeq {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getDISCCNCLDtlSeq();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setDISCCNCLDtlSeq((BigDecimal)value);
            }
        }
        ,
        Approvedflag {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getApprovedflag();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setApprovedflag((String)value);
            }
        }
        ,
        PVTHDRSEQ1 {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getPVTHDRSEQ1();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setPVTHDRSEQ1((BigDecimal)value);
            }
        }
        ,
        PVTStageLOVVO1 {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getPVTStageLOVVO1();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PvtStatusMstLovVO1 {
            public Object get(discountsearchVORowImpl obj) {
                return obj.getPvtStatusMstLovVO1();
            }

            public void put(discountsearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(discountsearchVORowImpl object);

        public abstract void put(discountsearchVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PVTNUM = AttributesEnum.PVTNum.index();
    public static final int CUSTFIRSTNAME = AttributesEnum.CustFirstName.index();
    public static final int CUSTEMAILID = AttributesEnum.CustEmailID.index();
    public static final int CUSTLASTNAME = AttributesEnum.CustLastName.index();
    public static final int CUSTMOBILENUM = AttributesEnum.CustMobilenum.index();
    public static final int ZONECODE = AttributesEnum.zonecode.index();
    public static final int SECTORCODE = AttributesEnum.SectorCode.index();
    public static final int PVTSTATUSID = AttributesEnum.PVTStatusID.index();
    public static final int PVTSTAGEID = AttributesEnum.PVTSTAGEID.index();
    public static final int PVTHDRSEQ = AttributesEnum.PVTHDRSEQ.index();
    public static final int CONTRACODE = AttributesEnum.Contracode.index();
    public static final int PVTAMTPAYABLE = AttributesEnum.PVTAMTPAYABLE.index();
    public static final int APPROVERREMARKS = AttributesEnum.ApproverRemarks.index();
    public static final int DISCPROMONAME = AttributesEnum.DISCPROMONAME.index();
    public static final int DISCCNCLTYPE = AttributesEnum.DISCCNCLTYPE.index();
    public static final int DISCPROMOCODE = AttributesEnum.DISCPROMOCODE.index();
    public static final int DISCCNCLHDRSEQ = AttributesEnum.DISCCNCLhdrSeq.index();
    public static final int DISCCNCLSTATUS = AttributesEnum.DISCCNCLSTATUS.index();
    public static final int PROMOEFFECTIVEDATETO = AttributesEnum.PromoeffectivedateTo.index();
    public static final int PROMOEFFECTIVEDATEFROM = AttributesEnum.Promoeffectivedatefrom.index();
    public static final int DISCCNCLHDRSEQ1 = AttributesEnum.DISCCNCLhdrSeq1.index();
    public static final int DISCCNCLDTLSEQ = AttributesEnum.DISCCNCLDtlSeq.index();
    public static final int APPROVEDFLAG = AttributesEnum.Approvedflag.index();
    public static final int PVTHDRSEQ1 = AttributesEnum.PVTHDRSEQ1.index();
    public static final int PVTSTAGELOVVO1 = AttributesEnum.PVTStageLOVVO1.index();
    public static final int PVTSTATUSMSTLOVVO1 = AttributesEnum.PvtStatusMstLovVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public discountsearchVORowImpl() {
    }

    /**
     * Gets PVTHeadersmsEO entity object.
     * @return the PVTHeadersmsEO
     */
    public EntityImpl getPVTHeadersmsEO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets PVTDiscCnclHeaderEO entity object.
     * @return the PVTDiscCnclHeaderEO
     */
    public PVTDiscCnclHeaderEOImpl getPVTDiscCnclHeaderEO() {
        return (PVTDiscCnclHeaderEOImpl)getEntity(1);
    }

    /**
     * Gets PVTDiscCnclDetailEO entity object.
     * @return the PVTDiscCnclDetailEO
     */
    public PVTDiscCnclDetailEOImpl getPVTDiscCnclDetailEO() {
        return (PVTDiscCnclDetailEOImpl)getEntity(2);
    }

    /**
     * Gets the attribute value for PVT_Num using the alias name PVTNum.
     * @return the PVT_Num
     */
    public String getPVTNum() {
        return (String) getAttributeInternal(PVTNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for PVT_Num using the alias name PVTNum.
     * @param value value to set the PVT_Num
     */
    public void setPVTNum(String value) {
        setAttributeInternal(PVTNUM, value);
    }

    /**
     * Gets the attribute value for Cust_First_Name using the alias name CustFirstName.
     * @return the Cust_First_Name
     */
    public String getCustFirstName() {
        return (String) getAttributeInternal(CUSTFIRSTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for Cust_First_Name using the alias name CustFirstName.
     * @param value value to set the Cust_First_Name
     */
    public void setCustFirstName(String value) {
        setAttributeInternal(CUSTFIRSTNAME, value);
    }

    /**
     * Gets the attribute value for Cust_Email_ID using the alias name CustEmailID.
     * @return the Cust_Email_ID
     */
    public String getCustEmailID() {
        return (String) getAttributeInternal(CUSTEMAILID);
    }

    /**
     * Sets <code>value</code> as attribute value for Cust_Email_ID using the alias name CustEmailID.
     * @param value value to set the Cust_Email_ID
     */
    public void setCustEmailID(String value) {
        setAttributeInternal(CUSTEMAILID, value);
    }

    /**
     * Gets the attribute value for Cust_Last_Name using the alias name CustLastName.
     * @return the Cust_Last_Name
     */
    public String getCustLastName() {
        return (String) getAttributeInternal(CUSTLASTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for Cust_Last_Name using the alias name CustLastName.
     * @param value value to set the Cust_Last_Name
     */
    public void setCustLastName(String value) {
        setAttributeInternal(CUSTLASTNAME, value);
    }

    /**
     * Gets the attribute value for Cust_Mobile_num using the alias name CustMobilenum.
     * @return the Cust_Mobile_num
     */
    public BigDecimal getCustMobilenum() {
        return (BigDecimal) getAttributeInternal(CUSTMOBILENUM);
    }

    /**
     * Sets <code>value</code> as attribute value for Cust_Mobile_num using the alias name CustMobilenum.
     * @param value value to set the Cust_Mobile_num
     */
    public void setCustMobilenum(BigDecimal value) {
        setAttributeInternal(CUSTMOBILENUM, value);
    }

    /**
     * Gets the attribute value for zone_code using the alias name zonecode.
     * @return the zone_code
     */
    public String getzonecode() {
        return (String) getAttributeInternal(ZONECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for zone_code using the alias name zonecode.
     * @param value value to set the zone_code
     */
    public void setzonecode(String value) {
        setAttributeInternal(ZONECODE, value);
    }

    /**
     * Gets the attribute value for Sector_Code using the alias name SectorCode.
     * @return the Sector_Code
     */
    public String getSectorCode() {
        return (String) getAttributeInternal(SECTORCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for Sector_Code using the alias name SectorCode.
     * @param value value to set the Sector_Code
     */
    public void setSectorCode(String value) {
        setAttributeInternal(SECTORCODE, value);
    }

    /**
     * Gets the attribute value for PVT_Status_ID using the alias name PVTStatusID.
     * @return the PVT_Status_ID
     */
    public Integer getPVTStatusID() {
        return (Integer) getAttributeInternal(PVTSTATUSID);
    }

    /**
     * Sets <code>value</code> as attribute value for PVT_Status_ID using the alias name PVTStatusID.
     * @param value value to set the PVT_Status_ID
     */
    public void setPVTStatusID(Integer value) {
        setAttributeInternal(PVTSTATUSID, value);
    }

    /**
     * Gets the attribute value for PVT_STAGE_ID using the alias name PVTSTAGEID.
     * @return the PVT_STAGE_ID
     */
    public Integer getPVTSTAGEID() {
        return (Integer) getAttributeInternal(PVTSTAGEID);
    }

    /**
     * Sets <code>value</code> as attribute value for PVT_STAGE_ID using the alias name PVTSTAGEID.
     * @param value value to set the PVT_STAGE_ID
     */
    public void setPVTSTAGEID(Integer value) {
        setAttributeInternal(PVTSTAGEID, value);
    }

    /**
     * Gets the attribute value for PVT_HDR_SEQ using the alias name PVTHDRSEQ.
     * @return the PVT_HDR_SEQ
     */
    public BigDecimal getPVTHDRSEQ() {
        return (BigDecimal) getAttributeInternal(PVTHDRSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for PVT_HDR_SEQ using the alias name PVTHDRSEQ.
     * @param value value to set the PVT_HDR_SEQ
     */
    public void setPVTHDRSEQ(BigDecimal value) {
        setAttributeInternal(PVTHDRSEQ, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Contracode.
     * @return the Contracode
     */
    public Integer getContracode() {
        return (Integer) getAttributeInternal(CONTRACODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Contracode.
     * @param value value to set the  Contracode
     */
    public void setContracode(Integer value) {
        setAttributeInternal(CONTRACODE, value);
    }

    /**
     * Gets the attribute value for PVT_AMT_PAYABLE using the alias name PVTAMTPAYABLE.
     * @return the PVT_AMT_PAYABLE
     */
    public BigDecimal getPVTAMTPAYABLE() {
        return (BigDecimal) getAttributeInternal(PVTAMTPAYABLE);
    }

    /**
     * Sets <code>value</code> as attribute value for PVT_AMT_PAYABLE using the alias name PVTAMTPAYABLE.
     * @param value value to set the PVT_AMT_PAYABLE
     */
    public void setPVTAMTPAYABLE(BigDecimal value) {
        setAttributeInternal(PVTAMTPAYABLE, value);
    }

    /**
     * Gets the attribute value for Approver_Remarks using the alias name ApproverRemarks.
     * @return the Approver_Remarks
     */
    public String getApproverRemarks() {
        return (String) getAttributeInternal(APPROVERREMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for Approver_Remarks using the alias name ApproverRemarks.
     * @param value value to set the Approver_Remarks
     */
    public void setApproverRemarks(String value) {
        setAttributeInternal(APPROVERREMARKS, value);
    }

    /**
     * Gets the attribute value for DISC_PROMO_NAME using the alias name DISCPROMONAME.
     * @return the DISC_PROMO_NAME
     */
    public String getDISCPROMONAME() {
        return (String) getAttributeInternal(DISCPROMONAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DISC_PROMO_NAME using the alias name DISCPROMONAME.
     * @param value value to set the DISC_PROMO_NAME
     */
    public void setDISCPROMONAME(String value) {
        setAttributeInternal(DISCPROMONAME, value);
    }

    /**
     * Gets the attribute value for DISC_CNCL_TYPE using the alias name DISCCNCLTYPE.
     * @return the DISC_CNCL_TYPE
     */
    public String getDISCCNCLTYPE() {
        return (String) getAttributeInternal(DISCCNCLTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for DISC_CNCL_TYPE using the alias name DISCCNCLTYPE.
     * @param value value to set the DISC_CNCL_TYPE
     */
    public void setDISCCNCLTYPE(String value) {
        setAttributeInternal(DISCCNCLTYPE, value);
    }

    /**
     * Gets the attribute value for DISC_PROMO_CODE using the alias name DISCPROMOCODE.
     * @return the DISC_PROMO_CODE
     */
    public String getDISCPROMOCODE() {
        return (String) getAttributeInternal(DISCPROMOCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for DISC_PROMO_CODE using the alias name DISCPROMOCODE.
     * @param value value to set the DISC_PROMO_CODE
     */
    public void setDISCPROMOCODE(String value) {
        setAttributeInternal(DISCPROMOCODE, value);
    }

    /**
     * Gets the attribute value for DISC_CNCL_hdr_Seq using the alias name DISCCNCLhdrSeq.
     * @return the DISC_CNCL_hdr_Seq
     */
    public BigDecimal getDISCCNCLhdrSeq() {
        return (BigDecimal) getAttributeInternal(DISCCNCLHDRSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for DISC_CNCL_hdr_Seq using the alias name DISCCNCLhdrSeq.
     * @param value value to set the DISC_CNCL_hdr_Seq
     */
    public void setDISCCNCLhdrSeq(BigDecimal value) {
        setAttributeInternal(DISCCNCLHDRSEQ, value);
    }

    /**
     * Gets the attribute value for DISC_CNCL_STATUS using the alias name DISCCNCLSTATUS.
     * @return the DISC_CNCL_STATUS
     */
    public Integer getDISCCNCLSTATUS() {
        return (Integer) getAttributeInternal(DISCCNCLSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for DISC_CNCL_STATUS using the alias name DISCCNCLSTATUS.
     * @param value value to set the DISC_CNCL_STATUS
     */
    public void setDISCCNCLSTATUS(Integer value) {
        setAttributeInternal(DISCCNCLSTATUS, value);
    }

    /**
     * Gets the attribute value for Promo_effective_date_To using the alias name PromoeffectivedateTo.
     * @return the Promo_effective_date_To
     */
    public Timestamp getPromoeffectivedateTo() {
        return (Timestamp) getAttributeInternal(PROMOEFFECTIVEDATETO);
    }

    /**
     * Sets <code>value</code> as attribute value for Promo_effective_date_To using the alias name PromoeffectivedateTo.
     * @param value value to set the Promo_effective_date_To
     */
    public void setPromoeffectivedateTo(Timestamp value) {
        setAttributeInternal(PROMOEFFECTIVEDATETO, value);
    }

    /**
     * Gets the attribute value for Promo_effective_date_from using the alias name Promoeffectivedatefrom.
     * @return the Promo_effective_date_from
     */
    public Timestamp getPromoeffectivedatefrom() {
        return (Timestamp) getAttributeInternal(PROMOEFFECTIVEDATEFROM);
    }

    /**
     * Sets <code>value</code> as attribute value for Promo_effective_date_from using the alias name Promoeffectivedatefrom.
     * @param value value to set the Promo_effective_date_from
     */
    public void setPromoeffectivedatefrom(Timestamp value) {
        setAttributeInternal(PROMOEFFECTIVEDATEFROM, value);
    }

    /**
     * Gets the attribute value for DISC_CNCL_hdr_Seq using the alias name DISCCNCLhdrSeq1.
     * @return the DISC_CNCL_hdr_Seq
     */
    public BigDecimal getDISCCNCLhdrSeq1() {
        return (BigDecimal) getAttributeInternal(DISCCNCLHDRSEQ1);
    }

    /**
     * Sets <code>value</code> as attribute value for DISC_CNCL_hdr_Seq using the alias name DISCCNCLhdrSeq1.
     * @param value value to set the DISC_CNCL_hdr_Seq
     */
    public void setDISCCNCLhdrSeq1(BigDecimal value) {
        setAttributeInternal(DISCCNCLHDRSEQ1, value);
    }

    /**
     * Gets the attribute value for DISC_CNCL_Dtl_Seq using the alias name DISCCNCLDtlSeq.
     * @return the DISC_CNCL_Dtl_Seq
     */
    public BigDecimal getDISCCNCLDtlSeq() {
        return (BigDecimal) getAttributeInternal(DISCCNCLDTLSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for DISC_CNCL_Dtl_Seq using the alias name DISCCNCLDtlSeq.
     * @param value value to set the DISC_CNCL_Dtl_Seq
     */
    public void setDISCCNCLDtlSeq(BigDecimal value) {
        setAttributeInternal(DISCCNCLDTLSEQ, value);
    }

    /**
     * Gets the attribute value for Approved_flag using the alias name Approvedflag.
     * @return the Approved_flag
     */
    public String getApprovedflag() {
        return (String) getAttributeInternal(APPROVEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for Approved_flag using the alias name Approvedflag.
     * @param value value to set the Approved_flag
     */
    public void setApprovedflag(String value) {
        setAttributeInternal(APPROVEDFLAG, value);
    }

    /**
     * Gets the attribute value for PVT_HDR_SEQ using the alias name PVTHDRSEQ1.
     * @return the PVT_HDR_SEQ
     */
    public BigDecimal getPVTHDRSEQ1() {
        return (BigDecimal) getAttributeInternal(PVTHDRSEQ1);
    }

    /**
     * Sets <code>value</code> as attribute value for PVT_HDR_SEQ using the alias name PVTHDRSEQ1.
     * @param value value to set the PVT_HDR_SEQ
     */
    public void setPVTHDRSEQ1(BigDecimal value) {
        setAttributeInternal(PVTHDRSEQ1, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PVTStageLOVVO1.
     */
    public RowSet getPVTStageLOVVO1() {
        return (RowSet)getAttributeInternal(PVTSTAGELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PvtStatusMstLovVO1.
     */
    public RowSet getPvtStatusMstLovVO1() {
        return (RowSet)getAttributeInternal(PVTSTATUSMSTLOVVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
