package com.imum.cpms.model.transactions.vo;

import java.math.BigDecimal;

import java.sql.Date;
import java.sql.Timestamp;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 29 11:52:36 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GenAccLogUVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CreatedBy {
            public Object get(GenAccLogUVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(GenAccLogUVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(GenAccLogUVORowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(GenAccLogUVORowImpl obj, Object value) {
                obj.setCreatedDate((Timestamp)value);
            }
        }
        ,
        DiscAmt {
            public Object get(GenAccLogUVORowImpl obj) {
                return obj.getDiscAmt();
            }

            public void put(GenAccLogUVORowImpl obj, Object value) {
                obj.setDiscAmt((BigDecimal)value);
            }
        }
        ,
        InstQuotaseq {
            public Object get(GenAccLogUVORowImpl obj) {
                return obj.getInstQuotaseq();
            }

            public void put(GenAccLogUVORowImpl obj, Object value) {
                obj.setInstQuotaseq((BigDecimal)value);
            }
        }
        ,
        PVTHDRSEQ {
            public Object get(GenAccLogUVORowImpl obj) {
                return obj.getPVTHDRSEQ();
            }

            public void put(GenAccLogUVORowImpl obj, Object value) {
                obj.setPVTHDRSEQ((BigDecimal)value);
            }
        }
        ,
        Salehdrseq {
            public Object get(GenAccLogUVORowImpl obj) {
                return obj.getSalehdrseq();
            }

            public void put(GenAccLogUVORowImpl obj, Object value) {
                obj.setSalehdrseq((BigDecimal)value);
            }
        }
        ,
        Updatedby {
            public Object get(GenAccLogUVORowImpl obj) {
                return obj.getUpdatedby();
            }

            public void put(GenAccLogUVORowImpl obj, Object value) {
                obj.setUpdatedby((String)value);
            }
        }
        ,
        Updateddate {
            public Object get(GenAccLogUVORowImpl obj) {
                return obj.getUpdateddate();
            }

            public void put(GenAccLogUVORowImpl obj, Object value) {
                obj.setUpdateddate((Timestamp)value);
            }
        }
        ,
        accamount {
            public Object get(GenAccLogUVORowImpl obj) {
                return obj.getaccamount();
            }

            public void put(GenAccLogUVORowImpl obj, Object value) {
                obj.setaccamount((BigDecimal)value);
            }
        }
        ,
        accdate {
            public Object get(GenAccLogUVORowImpl obj) {
                return obj.getaccdate();
            }

            public void put(GenAccLogUVORowImpl obj, Object value) {
                obj.setaccdate((Date)value);
            }
        }
        ,
        acclogseq {
            public Object get(GenAccLogUVORowImpl obj) {
                return obj.getacclogseq();
            }

            public void put(GenAccLogUVORowImpl obj, Object value) {
                obj.setacclogseq((BigDecimal)value);
            }
        }
        ,
        accprocessflg {
            public Object get(GenAccLogUVORowImpl obj) {
                return obj.getaccprocessflg();
            }

            public void put(GenAccLogUVORowImpl obj, Object value) {
                obj.setaccprocessflg((String)value);
            }
        }
        ,
        accseq {
            public Object get(GenAccLogUVORowImpl obj) {
                return obj.getaccseq();
            }

            public void put(GenAccLogUVORowImpl obj, Object value) {
                obj.setaccseq((BigDecimal)value);
            }
        }
        ,
        accsource {
            public Object get(GenAccLogUVORowImpl obj) {
                return obj.getaccsource();
            }

            public void put(GenAccLogUVORowImpl obj, Object value) {
                obj.setaccsource((Integer)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(GenAccLogUVORowImpl object);

        public abstract void put(GenAccLogUVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int DISCAMT = AttributesEnum.DiscAmt.index();
    public static final int INSTQUOTASEQ = AttributesEnum.InstQuotaseq.index();
    public static final int PVTHDRSEQ = AttributesEnum.PVTHDRSEQ.index();
    public static final int SALEHDRSEQ = AttributesEnum.Salehdrseq.index();
    public static final int UPDATEDBY = AttributesEnum.Updatedby.index();
    public static final int UPDATEDDATE = AttributesEnum.Updateddate.index();
    public static final int ACCAMOUNT = AttributesEnum.accamount.index();
    public static final int ACCDATE = AttributesEnum.accdate.index();
    public static final int ACCLOGSEQ = AttributesEnum.acclogseq.index();
    public static final int ACCPROCESSFLG = AttributesEnum.accprocessflg.index();
    public static final int ACCSEQ = AttributesEnum.accseq.index();
    public static final int ACCSOURCE = AttributesEnum.accsource.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GenAccLogUVORowImpl() {
    }

    /**
     * Gets GenAccLogEO entity object.
     * @return the GenAccLogEO
     */
    public EntityImpl getGenAccLogEO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for Created_By using the alias name CreatedBy.
     * @return the Created_By
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for Created_By using the alias name CreatedBy.
     * @param value value to set the Created_By
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Created_Date using the alias name CreatedDate.
     * @return the Created_Date
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for Created_Date using the alias name CreatedDate.
     * @param value value to set the Created_Date
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Disc_Amt using the alias name DiscAmt.
     * @return the Disc_Amt
     */
    public BigDecimal getDiscAmt() {
        return (BigDecimal) getAttributeInternal(DISCAMT);
    }

    /**
     * Sets <code>value</code> as attribute value for Disc_Amt using the alias name DiscAmt.
     * @param value value to set the Disc_Amt
     */
    public void setDiscAmt(BigDecimal value) {
        setAttributeInternal(DISCAMT, value);
    }

    /**
     * Gets the attribute value for Inst_Quota_seq using the alias name InstQuotaseq.
     * @return the Inst_Quota_seq
     */
    public BigDecimal getInstQuotaseq() {
        return (BigDecimal) getAttributeInternal(INSTQUOTASEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for Inst_Quota_seq using the alias name InstQuotaseq.
     * @param value value to set the Inst_Quota_seq
     */
    public void setInstQuotaseq(BigDecimal value) {
        setAttributeInternal(INSTQUOTASEQ, value);
    }

    /**
     * Gets the attribute value for PVT_HDR_SEQ using the alias name PVTHDRSEQ.
     * @return the PVT_HDR_SEQ
     */
    public BigDecimal getPVTHDRSEQ() {
        return (BigDecimal) getAttributeInternal(PVTHDRSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for PVT_HDR_SEQ using the alias name PVTHDRSEQ.
     * @param value value to set the PVT_HDR_SEQ
     */
    public void setPVTHDRSEQ(BigDecimal value) {
        setAttributeInternal(PVTHDRSEQ, value);
    }

    /**
     * Gets the attribute value for Sale_hdr_seq using the alias name Salehdrseq.
     * @return the Sale_hdr_seq
     */
    public BigDecimal getSalehdrseq() {
        return (BigDecimal) getAttributeInternal(SALEHDRSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for Sale_hdr_seq using the alias name Salehdrseq.
     * @param value value to set the Sale_hdr_seq
     */
    public void setSalehdrseq(BigDecimal value) {
        setAttributeInternal(SALEHDRSEQ, value);
    }

    /**
     * Gets the attribute value for Updated_by using the alias name Updatedby.
     * @return the Updated_by
     */
    public String getUpdatedby() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for Updated_by using the alias name Updatedby.
     * @param value value to set the Updated_by
     */
    public void setUpdatedby(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for Updated_date using the alias name Updateddate.
     * @return the Updated_date
     */
    public Timestamp getUpdateddate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for Updated_date using the alias name Updateddate.
     * @param value value to set the Updated_date
     */
    public void setUpdateddate(Timestamp value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for acc_amount using the alias name accamount.
     * @return the acc_amount
     */
    public BigDecimal getaccamount() {
        return (BigDecimal) getAttributeInternal(ACCAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for acc_amount using the alias name accamount.
     * @param value value to set the acc_amount
     */
    public void setaccamount(BigDecimal value) {
        setAttributeInternal(ACCAMOUNT, value);
    }

    /**
     * Gets the attribute value for acc_date using the alias name accdate.
     * @return the acc_date
     */
    public Date getaccdate() {
        return (Date) getAttributeInternal(ACCDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for acc_date using the alias name accdate.
     * @param value value to set the acc_date
     */
    public void setaccdate(Date value) {
        setAttributeInternal(ACCDATE, value);
    }

    /**
     * Gets the attribute value for acc_log_seq using the alias name acclogseq.
     * @return the acc_log_seq
     */
    public BigDecimal getacclogseq() {
        return (BigDecimal) getAttributeInternal(ACCLOGSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for acc_log_seq using the alias name acclogseq.
     * @param value value to set the acc_log_seq
     */
    public void setacclogseq(BigDecimal value) {
        setAttributeInternal(ACCLOGSEQ, value);
    }

    /**
     * Gets the attribute value for acc_process_flg using the alias name accprocessflg.
     * @return the acc_process_flg
     */
    public String getaccprocessflg() {
        return (String) getAttributeInternal(ACCPROCESSFLG);
    }

    /**
     * Sets <code>value</code> as attribute value for acc_process_flg using the alias name accprocessflg.
     * @param value value to set the acc_process_flg
     */
    public void setaccprocessflg(String value) {
        setAttributeInternal(ACCPROCESSFLG, value);
    }

    /**
     * Gets the attribute value for acc_seq using the alias name accseq.
     * @return the acc_seq
     */
    public BigDecimal getaccseq() {
        return (BigDecimal) getAttributeInternal(ACCSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for acc_seq using the alias name accseq.
     * @param value value to set the acc_seq
     */
    public void setaccseq(BigDecimal value) {
        setAttributeInternal(ACCSEQ, value);
    }

    /**
     * Gets the attribute value for acc_source using the alias name accsource.
     * @return the acc_source
     */
    public Integer getaccsource() {
        return (Integer) getAttributeInternal(ACCSOURCE);
    }

    /**
     * Sets <code>value</code> as attribute value for acc_source using the alias name accsource.
     * @param value value to set the acc_source
     */
    public void setaccsource(Integer value) {
        setAttributeInternal(ACCSOURCE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
