package com.imum.cpms.model.transactions.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 05 17:02:43 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GenEventDetailsUVORowImpl extends ViewRowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public GenEventDetailsUVORowImpl() {
    }

    /**
     * Gets GenEventDetailsEO entity object.
     * @return the GenEventDetailsEO
     */
    public EntityImpl getGenEventDetailsEO() {
        return (EntityImpl)getEntity(0);
    }
}
