package com.imum.cpms.model.transactions.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 12 15:32:11 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PILocationVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        HHSNo {
            public Object get(PILocationVORowImpl obj) {
                return obj.getHHSNo();
            }

            public void put(PILocationVORowImpl obj, Object value) {
                obj.setHHSNo((String)value);
            }
        }
        ,
        PILocationVO1 {
            public Object get(PILocationVORowImpl obj) {
                return obj.getPILocationVO1();
            }

            public void put(PILocationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PILocationVORowImpl object);

        public abstract void put(PILocationVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HHSNO = AttributesEnum.HHSNo.index();
    public static final int PILOCATIONVO1 = AttributesEnum.PILocationVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PILocationVORowImpl() {
    }


    /**
     * Gets the attribute value for the calculated attribute HHSNo.
     * @return the HHSNo
     */
    public String getHHSNo() {
        return (String) getAttributeInternal(HHSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HHSNo.
     * @param value value to set the  HHSNo
     */
    public void setHHSNo(String value) {
        setAttributeInternal(HHSNO, value);
    }


    /**
     * Gets the view accessor <code>RowSet</code> PILocationVO1.
     */
    public RowSet getPILocationVO1() {
        return (RowSet)getAttributeInternal(PILOCATIONVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
