package com.imum.cpms.model.transactions.vo;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 10 12:22:41 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class pissupVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PIid {
            public Object get(pissupVORowImpl obj) {
                return obj.getPIid();
            }

            public void put(pissupVORowImpl obj, Object value) {
                obj.setPIid((String)value);
            }
        }
        ,
        Supid {
            public Object get(pissupVORowImpl obj) {
                return obj.getSupid();
            }

            public void put(pissupVORowImpl obj, Object value) {
                obj.setSupid((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(pissupVORowImpl object);

        public abstract void put(pissupVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int PIID = AttributesEnum.PIid.index();
    public static final int SUPID = AttributesEnum.Supid.index();

    /**
     * This is the default constructor (do not remove).
     */
    public pissupVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute PIid.
     * @return the PIid
     */
    public String getPIid() {
        return (String) getAttributeInternal(PIID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PIid.
     * @param value value to set the  PIid
     */
    public void setPIid(String value) {
        setAttributeInternal(PIID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Supid.
     * @return the Supid
     */
    public String getSupid() {
        return (String) getAttributeInternal(SUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Supid.
     * @param value value to set the  Supid
     */
    public void setSupid(String value) {
        setAttributeInternal(SUPID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
