package com.imum.cpms.model.transactions.vo;



import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 25 14:58:45 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PoundBayDetailVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Baynum {
            public Object get(PoundBayDetailVORowImpl obj) {
                return obj.getBaynum();
            }

            public void put(PoundBayDetailVORowImpl obj, Object value) {
                obj.setBaynum((Integer)value);
            }
        }
        ,
        Baystatus {
            public Object get(PoundBayDetailVORowImpl obj) {
                return obj.getBaystatus();
            }

            public void put(PoundBayDetailVORowImpl obj, Object value) {
                obj.setBaystatus((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PoundBayDetailVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PoundBayDetailVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(PoundBayDetailVORowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(PoundBayDetailVORowImpl obj, Object value) {
                obj.setCreatedDate((Timestamp)value);
            }
        }
        ,
        POUNDLocationID {
            public Object get(PoundBayDetailVORowImpl obj) {
                return obj.getPOUNDLocationID();
            }

            public void put(PoundBayDetailVORowImpl obj, Object value) {
                obj.setPOUNDLocationID((Integer)value);
            }
        }
        ,
        PVTHDRSEQ {
            public Object get(PoundBayDetailVORowImpl obj) {
                return obj.getPVTHDRSEQ();
            }

            public void put(PoundBayDetailVORowImpl obj, Object value) {
                obj.setPVTHDRSEQ((BigDecimal)value);
            }
        }
        ,
        PoundbaydetailSeq {
            public Object get(PoundBayDetailVORowImpl obj) {
                return obj.getPoundbaydetailSeq();
            }

            public void put(PoundBayDetailVORowImpl obj, Object value) {
                obj.setPoundbaydetailSeq((BigDecimal)value);
            }
        }
        ,
        Updatedby {
            public Object get(PoundBayDetailVORowImpl obj) {
                return obj.getUpdatedby();
            }

            public void put(PoundBayDetailVORowImpl obj, Object value) {
                obj.setUpdatedby((String)value);
            }
        }
        ,
        Updateddate {
            public Object get(PoundBayDetailVORowImpl obj) {
                return obj.getUpdateddate();
            }

            public void put(PoundBayDetailVORowImpl obj, Object value) {
                obj.setUpdateddate((Timestamp)value);
            }
        }
        ,
        PVTNumber {
            public Object get(PoundBayDetailVORowImpl obj) {
                return obj.getPVTNumber();
            }

            public void put(PoundBayDetailVORowImpl obj, Object value) {
                obj.setPVTNumber((String)value);
            }
        }
        ,
        PoundBayLocation {
            public Object get(PoundBayDetailVORowImpl obj) {
                return obj.getPoundBayLocation();
            }

            public void put(PoundBayDetailVORowImpl obj, Object value) {
                obj.setPoundBayLocation((Integer)value);
            }
        }
        ,
        PoundBayNumber {
            public Object get(PoundBayDetailVORowImpl obj) {
                return obj.getPoundBayNumber();
            }

            public void put(PoundBayDetailVORowImpl obj, Object value) {
                obj.setPoundBayNumber((Integer)value);
            }
        }
        ,
        PoundLocationLVO1 {
            public Object get(PoundBayDetailVORowImpl obj) {
                return obj.getPoundLocationLVO1();
            }

            public void put(PoundBayDetailVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BayNumberLVO1 {
            public Object get(PoundBayDetailVORowImpl obj) {
                return obj.getBayNumberLVO1();
            }

            public void put(PoundBayDetailVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PoundBayDetailVORowImpl object);

        public abstract void put(PoundBayDetailVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BAYNUM = AttributesEnum.Baynum.index();
    public static final int BAYSTATUS = AttributesEnum.Baystatus.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int POUNDLOCATIONID = AttributesEnum.POUNDLocationID.index();
    public static final int PVTHDRSEQ = AttributesEnum.PVTHDRSEQ.index();
    public static final int POUNDBAYDETAILSEQ = AttributesEnum.PoundbaydetailSeq.index();
    public static final int UPDATEDBY = AttributesEnum.Updatedby.index();
    public static final int UPDATEDDATE = AttributesEnum.Updateddate.index();
    public static final int PVTNUMBER = AttributesEnum.PVTNumber.index();
    public static final int POUNDBAYLOCATION = AttributesEnum.PoundBayLocation.index();
    public static final int POUNDBAYNUMBER = AttributesEnum.PoundBayNumber.index();
    public static final int POUNDLOCATIONLVO1 = AttributesEnum.PoundLocationLVO1.index();
    public static final int BAYNUMBERLVO1 = AttributesEnum.BayNumberLVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PoundBayDetailVORowImpl() {
    }

    /**
     * Gets PoundBayDetailEO entity object.
     * @return the PoundBayDetailEO
     */
    public EntityImpl getPoundBayDetailEO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for Bay_num using the alias name Baynum.
     * @return the Bay_num
     */
    public Integer getBaynum() {
        return (Integer) getAttributeInternal(BAYNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for Bay_num using the alias name Baynum.
     * @param value value to set the Bay_num
     */
    public void setBaynum(Integer value) {
        setAttributeInternal(BAYNUM, value);
    }

    /**
     * Gets the attribute value for Bay_status using the alias name Baystatus.
     * @return the Bay_status
     */
    public String getBaystatus() {
        return (String) getAttributeInternal(BAYSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for Bay_status using the alias name Baystatus.
     * @param value value to set the Bay_status
     */
    public void setBaystatus(String value) {
        setAttributeInternal(BAYSTATUS, value);
    }

    /**
     * Gets the attribute value for Created_By using the alias name CreatedBy.
     * @return the Created_By
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for Created_By using the alias name CreatedBy.
     * @param value value to set the Created_By
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Created_Date using the alias name CreatedDate.
     * @return the Created_Date
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for Created_Date using the alias name CreatedDate.
     * @param value value to set the Created_Date
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for POUND_Location_ID using the alias name POUNDLocationID.
     * @return the POUND_Location_ID
     */
    public Integer getPOUNDLocationID() {
        return (Integer) getAttributeInternal(POUNDLOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for POUND_Location_ID using the alias name POUNDLocationID.
     * @param value value to set the POUND_Location_ID
     */
    public void setPOUNDLocationID(Integer value) {
        setAttributeInternal(POUNDLOCATIONID, value);
    }

    /**
     * Gets the attribute value for PVT_HDR_SEQ using the alias name PVTHDRSEQ.
     * @return the PVT_HDR_SEQ
     */
    public BigDecimal getPVTHDRSEQ() {
        return (BigDecimal) getAttributeInternal(PVTHDRSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for PVT_HDR_SEQ using the alias name PVTHDRSEQ.
     * @param value value to set the PVT_HDR_SEQ
     */
    public void setPVTHDRSEQ(BigDecimal value) {
        setAttributeInternal(PVTHDRSEQ, value);
    }

    /**
     * Gets the attribute value for Pound_bay_detail_Seq using the alias name PoundbaydetailSeq.
     * @return the Pound_bay_detail_Seq
     */
    public BigDecimal getPoundbaydetailSeq() {
        return (BigDecimal) getAttributeInternal(POUNDBAYDETAILSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for Pound_bay_detail_Seq using the alias name PoundbaydetailSeq.
     * @param value value to set the Pound_bay_detail_Seq
     */
    public void setPoundbaydetailSeq(BigDecimal value) {
        setAttributeInternal(POUNDBAYDETAILSEQ, value);
    }

    /**
     * Gets the attribute value for Updated_by using the alias name Updatedby.
     * @return the Updated_by
     */
    public String getUpdatedby() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for Updated_by using the alias name Updatedby.
     * @param value value to set the Updated_by
     */
    public void setUpdatedby(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for Updated_date using the alias name Updateddate.
     * @return the Updated_date
     */
    public Timestamp getUpdateddate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for Updated_date using the alias name Updateddate.
     * @param value value to set the Updated_date
     */
    public void setUpdateddate(Timestamp value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PVTNumber.
     * @return the PVTNumber
     */
    public String getPVTNumber() {
        return (String) getAttributeInternal(PVTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PVTNumber.
     * @param value value to set the  PVTNumber
     */
    public void setPVTNumber(String value) {
        setAttributeInternal(PVTNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PoundBayLocation.
     * @return the PoundBayLocation
     */
    public Integer getPoundBayLocation() {
        return (Integer) getAttributeInternal(POUNDBAYLOCATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PoundBayLocation.
     * @param value value to set the  PoundBayLocation
     */
    public void setPoundBayLocation(Integer value) {
        setAttributeInternal(POUNDBAYLOCATION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PoundBayNumber.
     * @return the PoundBayNumber
     */
    public Integer getPoundBayNumber() {
        return (Integer) getAttributeInternal(POUNDBAYNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PoundBayNumber.
     * @param value value to set the  PoundBayNumber
     */
    public void setPoundBayNumber(Integer value) {
        setAttributeInternal(POUNDBAYNUMBER, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PoundLocationLVO1.
     */
    public RowSet getPoundLocationLVO1() {
        return (RowSet)getAttributeInternal(POUNDLOCATIONLVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BayNumberLVO1.
     */
    public RowSet getBayNumberLVO1() {
        return (RowSet)getAttributeInternal(BAYNUMBERLVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
    
    public void refreshPoundBayAllocLovs(){
            RowSet poundLoc = this.getPoundLocationLVO1(); 
            poundLoc.executeQuery();
            
            setPoundBayLocation(null);
            RowSet bayrow = this.getBayNumberLVO1();
            if(bayrow!=null){
                 bayrow.executeEmptyRowSet();
            }       
            setPoundBayNumber(null);
//            Row row = (Row)this.getPoundLocationLVO1().first(); 
//            if(row!=null){
//                Integer i = (Integer)row.getAttribute(0);
//                setPoundBayLocation(null);
//                //setPOUNDLocationID(i);
//            }
//            Row bayrow = (Row)this.getBayNumberLVO1().first(); 
//            if(bayrow!=null)
//            {
//                BigDecimal bay = (BigDecimal)bayrow.getAttribute(0);
//                BayNumberLVORowImpl bayImpl = (BayNumberLVORowImpl)bayrow;
//                //setBaynum(bayImpl.getBaynum());
//                setPoundBayNumber(null);
//            }
        }
}
