package com.imum.cpms.model.transactions.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 18 14:13:20 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PVTAUCTIONHeaderVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        AUCTIONHeaderseq {
            public Object get(PVTAUCTIONHeaderVORowImpl obj) {
                return obj.getAUCTIONHeaderseq();
            }

            public void put(PVTAUCTIONHeaderVORowImpl obj, Object value) {
                obj.setAUCTIONHeaderseq((BigDecimal)value);
            }
        }
        ,
        AUCTInitiationDate {
            public Object get(PVTAUCTIONHeaderVORowImpl obj) {
                return obj.getAUCTInitiationDate();
            }

            public void put(PVTAUCTIONHeaderVORowImpl obj, Object value) {
                obj.setAUCTInitiationDate((Timestamp)value);
            }
        }
        ,
        AuctHouseRefnum {
            public Object get(PVTAUCTIONHeaderVORowImpl obj) {
                return obj.getAuctHouseRefnum();
            }

            public void put(PVTAUCTIONHeaderVORowImpl obj, Object value) {
                obj.setAuctHouseRefnum((String)value);
            }
        }
        ,
        BatchStatusID {
            public Object get(PVTAUCTIONHeaderVORowImpl obj) {
                return obj.getBatchStatusID();
            }

            public void put(PVTAUCTIONHeaderVORowImpl obj, Object value) {
                obj.setBatchStatusID((Integer)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PVTAUCTIONHeaderVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PVTAUCTIONHeaderVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(PVTAUCTIONHeaderVORowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(PVTAUCTIONHeaderVORowImpl obj, Object value) {
                obj.setCreatedDate((Timestamp)value);
            }
        }
        ,
        PLATECNTID {
            public Object get(PVTAUCTIONHeaderVORowImpl obj) {
                return obj.getPLATECNTID();
            }

            public void put(PVTAUCTIONHeaderVORowImpl obj, Object value) {
                obj.setPLATECNTID((Integer)value);
            }
        }
        ,
        PLATECTGID {
            public Object get(PVTAUCTIONHeaderVORowImpl obj) {
                return obj.getPLATECTGID();
            }

            public void put(PVTAUCTIONHeaderVORowImpl obj, Object value) {
                obj.setPLATECTGID((Integer)value);
            }
        }
        ,
        PLATENUMBER {
            public Object get(PVTAUCTIONHeaderVORowImpl obj) {
                return obj.getPLATENUMBER();
            }

            public void put(PVTAUCTIONHeaderVORowImpl obj, Object value) {
                obj.setPLATENUMBER((String)value);
            }
        }
        ,
        PLATETYPEID {
            public Object get(PVTAUCTIONHeaderVORowImpl obj) {
                return obj.getPLATETYPEID();
            }

            public void put(PVTAUCTIONHeaderVORowImpl obj, Object value) {
                obj.setPLATETYPEID((Integer)value);
            }
        }
        ,
        PVTdatefrom {
            public Object get(PVTAUCTIONHeaderVORowImpl obj) {
                return obj.getPVTdatefrom();
            }

            public void put(PVTAUCTIONHeaderVORowImpl obj, Object value) {
                obj.setPVTdatefrom((Timestamp)value);
            }
        }
        ,
        PVTdateto {
            public Object get(PVTAUCTIONHeaderVORowImpl obj) {
                return obj.getPVTdateto();
            }

            public void put(PVTAUCTIONHeaderVORowImpl obj, Object value) {
                obj.setPVTdateto((Timestamp)value);
            }
        }
        ,
        SectorCode {
            public Object get(PVTAUCTIONHeaderVORowImpl obj) {
                return obj.getSectorCode();
            }

            public void put(PVTAUCTIONHeaderVORowImpl obj, Object value) {
                obj.setSectorCode((String)value);
            }
        }
        ,
        TotalPVTCount {
            public Object get(PVTAUCTIONHeaderVORowImpl obj) {
                return obj.getTotalPVTCount();
            }

            public void put(PVTAUCTIONHeaderVORowImpl obj, Object value) {
                obj.setTotalPVTCount((Integer)value);
            }
        }
        ,
        Updatedate {
            public Object get(PVTAUCTIONHeaderVORowImpl obj) {
                return obj.getUpdatedate();
            }

            public void put(PVTAUCTIONHeaderVORowImpl obj, Object value) {
                obj.setUpdatedate((Timestamp)value);
            }
        }
        ,
        Updatedby {
            public Object get(PVTAUCTIONHeaderVORowImpl obj) {
                return obj.getUpdatedby();
            }

            public void put(PVTAUCTIONHeaderVORowImpl obj, Object value) {
                obj.setUpdatedby((String)value);
            }
        }
        ,
        zonecode {
            public Object get(PVTAUCTIONHeaderVORowImpl obj) {
                return obj.getzonecode();
            }

            public void put(PVTAUCTIONHeaderVORowImpl obj, Object value) {
                obj.setzonecode((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PVTAUCTIONHeaderVORowImpl object);

        public abstract void put(PVTAUCTIONHeaderVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int AUCTIONHEADERSEQ = AttributesEnum.AUCTIONHeaderseq.index();
    public static final int AUCTINITIATIONDATE = AttributesEnum.AUCTInitiationDate.index();
    public static final int AUCTHOUSEREFNUM = AttributesEnum.AuctHouseRefnum.index();
    public static final int BATCHSTATUSID = AttributesEnum.BatchStatusID.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int PLATECNTID = AttributesEnum.PLATECNTID.index();
    public static final int PLATECTGID = AttributesEnum.PLATECTGID.index();
    public static final int PLATENUMBER = AttributesEnum.PLATENUMBER.index();
    public static final int PLATETYPEID = AttributesEnum.PLATETYPEID.index();
    public static final int PVTDATEFROM = AttributesEnum.PVTdatefrom.index();
    public static final int PVTDATETO = AttributesEnum.PVTdateto.index();
    public static final int SECTORCODE = AttributesEnum.SectorCode.index();
    public static final int TOTALPVTCOUNT = AttributesEnum.TotalPVTCount.index();
    public static final int UPDATEDATE = AttributesEnum.Updatedate.index();
    public static final int UPDATEDBY = AttributesEnum.Updatedby.index();
    public static final int ZONECODE = AttributesEnum.zonecode.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PVTAUCTIONHeaderVORowImpl() {
    }

    /**
     * Gets PVTAUCTIONHeaderEO entity object.
     * @return the PVTAUCTIONHeaderEO
     */
    public EntityImpl getPVTAUCTIONHeaderEO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for AUCTION_Header_seq using the alias name AUCTIONHeaderseq.
     * @return the AUCTION_Header_seq
     */
    public BigDecimal getAUCTIONHeaderseq() {
        return (BigDecimal) getAttributeInternal(AUCTIONHEADERSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for AUCTION_Header_seq using the alias name AUCTIONHeaderseq.
     * @param value value to set the AUCTION_Header_seq
     */
    public void setAUCTIONHeaderseq(BigDecimal value) {
        setAttributeInternal(AUCTIONHEADERSEQ, value);
    }

    /**
     * Gets the attribute value for AUCT_Initiation_Date using the alias name AUCTInitiationDate.
     * @return the AUCT_Initiation_Date
     */
    public Timestamp getAUCTInitiationDate() {
        return (Timestamp) getAttributeInternal(AUCTINITIATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for AUCT_Initiation_Date using the alias name AUCTInitiationDate.
     * @param value value to set the AUCT_Initiation_Date
     */
    public void setAUCTInitiationDate(Timestamp value) {
        setAttributeInternal(AUCTINITIATIONDATE, value);
    }

    /**
     * Gets the attribute value for Auct_House_Ref_num using the alias name AuctHouseRefnum.
     * @return the Auct_House_Ref_num
     */
    public String getAuctHouseRefnum() {
        return (String) getAttributeInternal(AUCTHOUSEREFNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for Auct_House_Ref_num using the alias name AuctHouseRefnum.
     * @param value value to set the Auct_House_Ref_num
     */
    public void setAuctHouseRefnum(String value) {
        setAttributeInternal(AUCTHOUSEREFNUM, value);
    }

    /**
     * Gets the attribute value for Batch_Status_ID using the alias name BatchStatusID.
     * @return the Batch_Status_ID
     */
    public Integer getBatchStatusID() {
        return (Integer) getAttributeInternal(BATCHSTATUSID);
    }

    /**
     * Sets <code>value</code> as attribute value for Batch_Status_ID using the alias name BatchStatusID.
     * @param value value to set the Batch_Status_ID
     */
    public void setBatchStatusID(Integer value) {
        setAttributeInternal(BATCHSTATUSID, value);
    }

    /**
     * Gets the attribute value for Created_By using the alias name CreatedBy.
     * @return the Created_By
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for Created_By using the alias name CreatedBy.
     * @param value value to set the Created_By
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Created_Date using the alias name CreatedDate.
     * @return the Created_Date
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for Created_Date using the alias name CreatedDate.
     * @param value value to set the Created_Date
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for PLATE_CNT_ID using the alias name PLATECNTID.
     * @return the PLATE_CNT_ID
     */
    public Integer getPLATECNTID() {
        return (Integer) getAttributeInternal(PLATECNTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PLATE_CNT_ID using the alias name PLATECNTID.
     * @param value value to set the PLATE_CNT_ID
     */
    public void setPLATECNTID(Integer value) {
        setAttributeInternal(PLATECNTID, value);
    }

    /**
     * Gets the attribute value for PLATE_CTG_ID using the alias name PLATECTGID.
     * @return the PLATE_CTG_ID
     */
    public Integer getPLATECTGID() {
        return (Integer) getAttributeInternal(PLATECTGID);
    }

    /**
     * Sets <code>value</code> as attribute value for PLATE_CTG_ID using the alias name PLATECTGID.
     * @param value value to set the PLATE_CTG_ID
     */
    public void setPLATECTGID(Integer value) {
        setAttributeInternal(PLATECTGID, value);
    }

    /**
     * Gets the attribute value for PLATE_NUMBER using the alias name PLATENUMBER.
     * @return the PLATE_NUMBER
     */
    public String getPLATENUMBER() {
        return (String) getAttributeInternal(PLATENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PLATE_NUMBER using the alias name PLATENUMBER.
     * @param value value to set the PLATE_NUMBER
     */
    public void setPLATENUMBER(String value) {
        setAttributeInternal(PLATENUMBER, value);
    }

    /**
     * Gets the attribute value for PLATE_TYPE_ID using the alias name PLATETYPEID.
     * @return the PLATE_TYPE_ID
     */
    public Integer getPLATETYPEID() {
        return (Integer) getAttributeInternal(PLATETYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for PLATE_TYPE_ID using the alias name PLATETYPEID.
     * @param value value to set the PLATE_TYPE_ID
     */
    public void setPLATETYPEID(Integer value) {
        setAttributeInternal(PLATETYPEID, value);
    }

    /**
     * Gets the attribute value for PVT_date_from using the alias name PVTdatefrom.
     * @return the PVT_date_from
     */
    public Timestamp getPVTdatefrom() {
        return (Timestamp) getAttributeInternal(PVTDATEFROM);
    }

    /**
     * Sets <code>value</code> as attribute value for PVT_date_from using the alias name PVTdatefrom.
     * @param value value to set the PVT_date_from
     */
    public void setPVTdatefrom(Timestamp value) {
        setAttributeInternal(PVTDATEFROM, value);
    }

    /**
     * Gets the attribute value for PVT_date_to using the alias name PVTdateto.
     * @return the PVT_date_to
     */
    public Timestamp getPVTdateto() {
        return (Timestamp) getAttributeInternal(PVTDATETO);
    }

    /**
     * Sets <code>value</code> as attribute value for PVT_date_to using the alias name PVTdateto.
     * @param value value to set the PVT_date_to
     */
    public void setPVTdateto(Timestamp value) {
        setAttributeInternal(PVTDATETO, value);
    }

    /**
     * Gets the attribute value for Sector_Code using the alias name SectorCode.
     * @return the Sector_Code
     */
    public String getSectorCode() {
        return (String) getAttributeInternal(SECTORCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for Sector_Code using the alias name SectorCode.
     * @param value value to set the Sector_Code
     */
    public void setSectorCode(String value) {
        setAttributeInternal(SECTORCODE, value);
    }

    /**
     * Gets the attribute value for Total_PVT_Count using the alias name TotalPVTCount.
     * @return the Total_PVT_Count
     */
    public Integer getTotalPVTCount() {
        return (Integer) getAttributeInternal(TOTALPVTCOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for Total_PVT_Count using the alias name TotalPVTCount.
     * @param value value to set the Total_PVT_Count
     */
    public void setTotalPVTCount(Integer value) {
        setAttributeInternal(TOTALPVTCOUNT, value);
    }

    /**
     * Gets the attribute value for Update_date using the alias name Updatedate.
     * @return the Update_date
     */
    public Timestamp getUpdatedate() {
        return (Timestamp) getAttributeInternal(UPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for Update_date using the alias name Updatedate.
     * @param value value to set the Update_date
     */
    public void setUpdatedate(Timestamp value) {
        setAttributeInternal(UPDATEDATE, value);
    }

    /**
     * Gets the attribute value for Updated_by using the alias name Updatedby.
     * @return the Updated_by
     */
    public String getUpdatedby() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for Updated_by using the alias name Updatedby.
     * @param value value to set the Updated_by
     */
    public void setUpdatedby(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for zone_code using the alias name zonecode.
     * @return the zone_code
     */
    public String getzonecode() {
        return (String) getAttributeInternal(ZONECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for zone_code using the alias name zonecode.
     * @param value value to set the zone_code
     */
    public void setzonecode(String value) {
        setAttributeInternal(ZONECODE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
