package com.imum.cpms.model.transactions.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 20 12:30:13 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PVTAUCTIONPVTDETAILSVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        AUCTIONHeaderseq {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getAUCTIONHeaderseq();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setAUCTIONHeaderseq((BigDecimal)value);
            }
        }
        ,
        AUCTIONPVTDTLseq {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getAUCTIONPVTDTLseq();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setAUCTIONPVTDTLseq((BigDecimal)value);
            }
        }
        ,
        AuctionVenue {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getAuctionVenue();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setAuctionVenue((String)value);
            }
        }
        ,
        Biddate {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getBiddate();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setBiddate((Timestamp)value);
            }
        }
        ,
        BidderName {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getBidderName();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setBidderName((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setCreatedDate((Timestamp)value);
            }
        }
        ,
        DoTApprvforAuctflag {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getDoTApprvforAuctflag();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setDoTApprvforAuctflag((String)value);
            }
        }
        ,
        FinalBidAmt {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getFinalBidAmt();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setFinalBidAmt((BigDecimal)value);
            }
        }
        ,
        NOCReceivedFlag {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getNOCReceivedFlag();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setNOCReceivedFlag((String)value);
            }
        }
        ,
        PLATECNTID {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getPLATECNTID();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setPLATECNTID((Integer)value);
            }
        }
        ,
        PLATECTGID {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getPLATECTGID();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setPLATECTGID((Integer)value);
            }
        }
        ,
        PLATENUMBER {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getPLATENUMBER();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setPLATENUMBER((String)value);
            }
        }
        ,
        PLATETYPEID {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getPLATETYPEID();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setPLATETYPEID((Integer)value);
            }
        }
        ,
        PVTAMTPAYABLE {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getPVTAMTPAYABLE();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setPVTAMTPAYABLE((BigDecimal)value);
            }
        }
        ,
        PVTHDRSEQ {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getPVTHDRSEQ();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setPVTHDRSEQ((BigDecimal)value);
            }
        }
        ,
        Remarks {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getRemarks();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        Updatedate {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getUpdatedate();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setUpdatedate((Timestamp)value);
            }
        }
        ,
        Updatedby {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getUpdatedby();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setUpdatedby((String)value);
            }
        }
        ,
        VEHCOLOURID {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getVEHCOLOURID();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setVEHCOLOURID((Integer)value);
            }
        }
        ,
        VEHMAKEID {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getVEHMAKEID();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setVEHMAKEID((Integer)value);
            }
        }
        ,
        VEHMODELID {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getVEHMODELID();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setVEHMODELID((Integer)value);
            }
        }
        ,
        ValuationAmt {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getValuationAmt();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setValuationAmt((BigDecimal)value);
            }
        }
        ,
        ValuationRecomdationID {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getValuationRecomdationID();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setValuationRecomdationID((Integer)value);
            }
        }
        ,
        VehReleasedflag {
            public Object get(PVTAUCTIONPVTDETAILSVORowImpl obj) {
                return obj.getVehReleasedflag();
            }

            public void put(PVTAUCTIONPVTDETAILSVORowImpl obj, Object value) {
                obj.setVehReleasedflag((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PVTAUCTIONPVTDETAILSVORowImpl object);

        public abstract void put(PVTAUCTIONPVTDETAILSVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int AUCTIONHEADERSEQ = AttributesEnum.AUCTIONHeaderseq.index();
    public static final int AUCTIONPVTDTLSEQ = AttributesEnum.AUCTIONPVTDTLseq.index();
    public static final int AUCTIONVENUE = AttributesEnum.AuctionVenue.index();
    public static final int BIDDATE = AttributesEnum.Biddate.index();
    public static final int BIDDERNAME = AttributesEnum.BidderName.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int DOTAPPRVFORAUCTFLAG = AttributesEnum.DoTApprvforAuctflag.index();
    public static final int FINALBIDAMT = AttributesEnum.FinalBidAmt.index();
    public static final int NOCRECEIVEDFLAG = AttributesEnum.NOCReceivedFlag.index();
    public static final int PLATECNTID = AttributesEnum.PLATECNTID.index();
    public static final int PLATECTGID = AttributesEnum.PLATECTGID.index();
    public static final int PLATENUMBER = AttributesEnum.PLATENUMBER.index();
    public static final int PLATETYPEID = AttributesEnum.PLATETYPEID.index();
    public static final int PVTAMTPAYABLE = AttributesEnum.PVTAMTPAYABLE.index();
    public static final int PVTHDRSEQ = AttributesEnum.PVTHDRSEQ.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int UPDATEDATE = AttributesEnum.Updatedate.index();
    public static final int UPDATEDBY = AttributesEnum.Updatedby.index();
    public static final int VEHCOLOURID = AttributesEnum.VEHCOLOURID.index();
    public static final int VEHMAKEID = AttributesEnum.VEHMAKEID.index();
    public static final int VEHMODELID = AttributesEnum.VEHMODELID.index();
    public static final int VALUATIONAMT = AttributesEnum.ValuationAmt.index();
    public static final int VALUATIONRECOMDATIONID = AttributesEnum.ValuationRecomdationID.index();
    public static final int VEHRELEASEDFLAG = AttributesEnum.VehReleasedflag.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PVTAUCTIONPVTDETAILSVORowImpl() {
    }

    /**
     * Gets PVTAUCTIONPVTDETAILSEO entity object.
     * @return the PVTAUCTIONPVTDETAILSEO
     */
    public EntityImpl getPVTAUCTIONPVTDETAILSEO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for AUCTION_Header_seq using the alias name AUCTIONHeaderseq.
     * @return the AUCTION_Header_seq
     */
    public BigDecimal getAUCTIONHeaderseq() {
        return (BigDecimal) getAttributeInternal(AUCTIONHEADERSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for AUCTION_Header_seq using the alias name AUCTIONHeaderseq.
     * @param value value to set the AUCTION_Header_seq
     */
    public void setAUCTIONHeaderseq(BigDecimal value) {
        setAttributeInternal(AUCTIONHEADERSEQ, value);
    }

    /**
     * Gets the attribute value for AUCTION_PVT_DTL_seq using the alias name AUCTIONPVTDTLseq.
     * @return the AUCTION_PVT_DTL_seq
     */
    public BigDecimal getAUCTIONPVTDTLseq() {
        return (BigDecimal) getAttributeInternal(AUCTIONPVTDTLSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for AUCTION_PVT_DTL_seq using the alias name AUCTIONPVTDTLseq.
     * @param value value to set the AUCTION_PVT_DTL_seq
     */
    public void setAUCTIONPVTDTLseq(BigDecimal value) {
        setAttributeInternal(AUCTIONPVTDTLSEQ, value);
    }

    /**
     * Gets the attribute value for Auction_Venue using the alias name AuctionVenue.
     * @return the Auction_Venue
     */
    public String getAuctionVenue() {
        return (String) getAttributeInternal(AUCTIONVENUE);
    }

    /**
     * Sets <code>value</code> as attribute value for Auction_Venue using the alias name AuctionVenue.
     * @param value value to set the Auction_Venue
     */
    public void setAuctionVenue(String value) {
        setAttributeInternal(AUCTIONVENUE, value);
    }

    /**
     * Gets the attribute value for Bid_date using the alias name Biddate.
     * @return the Bid_date
     */
    public Timestamp getBiddate() {
        return (Timestamp) getAttributeInternal(BIDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for Bid_date using the alias name Biddate.
     * @param value value to set the Bid_date
     */
    public void setBiddate(Timestamp value) {
        setAttributeInternal(BIDDATE, value);
    }

    /**
     * Gets the attribute value for Bidder_Name using the alias name BidderName.
     * @return the Bidder_Name
     */
    public String getBidderName() {
        return (String) getAttributeInternal(BIDDERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for Bidder_Name using the alias name BidderName.
     * @param value value to set the Bidder_Name
     */
    public void setBidderName(String value) {
        setAttributeInternal(BIDDERNAME, value);
    }

    /**
     * Gets the attribute value for Created_By using the alias name CreatedBy.
     * @return the Created_By
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for Created_By using the alias name CreatedBy.
     * @param value value to set the Created_By
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Created_Date using the alias name CreatedDate.
     * @return the Created_Date
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for Created_Date using the alias name CreatedDate.
     * @param value value to set the Created_Date
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for DoT_Apprv_for_Auct_flag using the alias name DoTApprvforAuctflag.
     * @return the DoT_Apprv_for_Auct_flag
     */
    public String getDoTApprvforAuctflag() {
        return (String) getAttributeInternal(DOTAPPRVFORAUCTFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for DoT_Apprv_for_Auct_flag using the alias name DoTApprvforAuctflag.
     * @param value value to set the DoT_Apprv_for_Auct_flag
     */
    public void setDoTApprvforAuctflag(String value) {
        setAttributeInternal(DOTAPPRVFORAUCTFLAG, value);
    }

    /**
     * Gets the attribute value for Final_Bid_Amt using the alias name FinalBidAmt.
     * @return the Final_Bid_Amt
     */
    public BigDecimal getFinalBidAmt() {
        return (BigDecimal) getAttributeInternal(FINALBIDAMT);
    }

    /**
     * Sets <code>value</code> as attribute value for Final_Bid_Amt using the alias name FinalBidAmt.
     * @param value value to set the Final_Bid_Amt
     */
    public void setFinalBidAmt(BigDecimal value) {
        setAttributeInternal(FINALBIDAMT, value);
    }

    /**
     * Gets the attribute value for NOC_Received_Flag using the alias name NOCReceivedFlag.
     * @return the NOC_Received_Flag
     */
    public String getNOCReceivedFlag() {
        return (String) getAttributeInternal(NOCRECEIVEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for NOC_Received_Flag using the alias name NOCReceivedFlag.
     * @param value value to set the NOC_Received_Flag
     */
    public void setNOCReceivedFlag(String value) {
        setAttributeInternal(NOCRECEIVEDFLAG, value);
    }

    /**
     * Gets the attribute value for PLATE_CNT_ID using the alias name PLATECNTID.
     * @return the PLATE_CNT_ID
     */
    public Integer getPLATECNTID() {
        return (Integer) getAttributeInternal(PLATECNTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PLATE_CNT_ID using the alias name PLATECNTID.
     * @param value value to set the PLATE_CNT_ID
     */
    public void setPLATECNTID(Integer value) {
        setAttributeInternal(PLATECNTID, value);
    }

    /**
     * Gets the attribute value for PLATE_CTG_ID using the alias name PLATECTGID.
     * @return the PLATE_CTG_ID
     */
    public Integer getPLATECTGID() {
        return (Integer) getAttributeInternal(PLATECTGID);
    }

    /**
     * Sets <code>value</code> as attribute value for PLATE_CTG_ID using the alias name PLATECTGID.
     * @param value value to set the PLATE_CTG_ID
     */
    public void setPLATECTGID(Integer value) {
        setAttributeInternal(PLATECTGID, value);
    }

    /**
     * Gets the attribute value for PLATE_NUMBER using the alias name PLATENUMBER.
     * @return the PLATE_NUMBER
     */
    public String getPLATENUMBER() {
        return (String) getAttributeInternal(PLATENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PLATE_NUMBER using the alias name PLATENUMBER.
     * @param value value to set the PLATE_NUMBER
     */
    public void setPLATENUMBER(String value) {
        setAttributeInternal(PLATENUMBER, value);
    }

    /**
     * Gets the attribute value for PLATE_TYPE_ID using the alias name PLATETYPEID.
     * @return the PLATE_TYPE_ID
     */
    public Integer getPLATETYPEID() {
        return (Integer) getAttributeInternal(PLATETYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for PLATE_TYPE_ID using the alias name PLATETYPEID.
     * @param value value to set the PLATE_TYPE_ID
     */
    public void setPLATETYPEID(Integer value) {
        setAttributeInternal(PLATETYPEID, value);
    }

    /**
     * Gets the attribute value for PVT_AMT_PAYABLE using the alias name PVTAMTPAYABLE.
     * @return the PVT_AMT_PAYABLE
     */
    public BigDecimal getPVTAMTPAYABLE() {
        return (BigDecimal) getAttributeInternal(PVTAMTPAYABLE);
    }

    /**
     * Sets <code>value</code> as attribute value for PVT_AMT_PAYABLE using the alias name PVTAMTPAYABLE.
     * @param value value to set the PVT_AMT_PAYABLE
     */
    public void setPVTAMTPAYABLE(BigDecimal value) {
        setAttributeInternal(PVTAMTPAYABLE, value);
    }

    /**
     * Gets the attribute value for PVT_HDR_SEQ using the alias name PVTHDRSEQ.
     * @return the PVT_HDR_SEQ
     */
    public BigDecimal getPVTHDRSEQ() {
        return (BigDecimal) getAttributeInternal(PVTHDRSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for PVT_HDR_SEQ using the alias name PVTHDRSEQ.
     * @param value value to set the PVT_HDR_SEQ
     */
    public void setPVTHDRSEQ(BigDecimal value) {
        setAttributeInternal(PVTHDRSEQ, value);
    }

    /**
     * Gets the attribute value for Remarks using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for Remarks using the alias name Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for Update_date using the alias name Updatedate.
     * @return the Update_date
     */
    public Timestamp getUpdatedate() {
        return (Timestamp) getAttributeInternal(UPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for Update_date using the alias name Updatedate.
     * @param value value to set the Update_date
     */
    public void setUpdatedate(Timestamp value) {
        setAttributeInternal(UPDATEDATE, value);
    }

    /**
     * Gets the attribute value for Updated_by using the alias name Updatedby.
     * @return the Updated_by
     */
    public String getUpdatedby() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for Updated_by using the alias name Updatedby.
     * @param value value to set the Updated_by
     */
    public void setUpdatedby(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for VEH_COLOUR_ID using the alias name VEHCOLOURID.
     * @return the VEH_COLOUR_ID
     */
    public Integer getVEHCOLOURID() {
        return (Integer) getAttributeInternal(VEHCOLOURID);
    }

    /**
     * Sets <code>value</code> as attribute value for VEH_COLOUR_ID using the alias name VEHCOLOURID.
     * @param value value to set the VEH_COLOUR_ID
     */
    public void setVEHCOLOURID(Integer value) {
        setAttributeInternal(VEHCOLOURID, value);
    }

    /**
     * Gets the attribute value for VEH_MAKE_ID using the alias name VEHMAKEID.
     * @return the VEH_MAKE_ID
     */
    public Integer getVEHMAKEID() {
        return (Integer) getAttributeInternal(VEHMAKEID);
    }

    /**
     * Sets <code>value</code> as attribute value for VEH_MAKE_ID using the alias name VEHMAKEID.
     * @param value value to set the VEH_MAKE_ID
     */
    public void setVEHMAKEID(Integer value) {
        setAttributeInternal(VEHMAKEID, value);
    }

    /**
     * Gets the attribute value for VEH_MODEL_ID using the alias name VEHMODELID.
     * @return the VEH_MODEL_ID
     */
    public Integer getVEHMODELID() {
        return (Integer) getAttributeInternal(VEHMODELID);
    }

    /**
     * Sets <code>value</code> as attribute value for VEH_MODEL_ID using the alias name VEHMODELID.
     * @param value value to set the VEH_MODEL_ID
     */
    public void setVEHMODELID(Integer value) {
        setAttributeInternal(VEHMODELID, value);
    }

    /**
     * Gets the attribute value for Valuation_Amt using the alias name ValuationAmt.
     * @return the Valuation_Amt
     */
    public BigDecimal getValuationAmt() {
        return (BigDecimal) getAttributeInternal(VALUATIONAMT);
    }

    /**
     * Sets <code>value</code> as attribute value for Valuation_Amt using the alias name ValuationAmt.
     * @param value value to set the Valuation_Amt
     */
    public void setValuationAmt(BigDecimal value) {
        setAttributeInternal(VALUATIONAMT, value);
    }

    /**
     * Gets the attribute value for Valuation_Recomdation_ID using the alias name ValuationRecomdationID.
     * @return the Valuation_Recomdation_ID
     */
    public Integer getValuationRecomdationID() {
        return (Integer) getAttributeInternal(VALUATIONRECOMDATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for Valuation_Recomdation_ID using the alias name ValuationRecomdationID.
     * @param value value to set the Valuation_Recomdation_ID
     */
    public void setValuationRecomdationID(Integer value) {
        setAttributeInternal(VALUATIONRECOMDATIONID, value);
    }

    /**
     * Gets the attribute value for Veh_Released_flag using the alias name VehReleasedflag.
     * @return the Veh_Released_flag
     */
    public String getVehReleasedflag() {
        return (String) getAttributeInternal(VEHRELEASEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for Veh_Released_flag using the alias name VehReleasedflag.
     * @param value value to set the Veh_Released_flag
     */
    public void setVehReleasedflag(String value) {
        setAttributeInternal(VEHRELEASEDFLAG, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
