package com.imum.cpms.model.transactions.vo;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 17 11:08:24 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PVTCategorizedChargesRVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PVTCategorizedChargesRVOImpl() {
    }

    /**
     * Returns the variable value for BindPvtHdrSeq.
     * @return variable value for BindPvtHdrSeq
     */
    public BigDecimal getBindPvtHdrSeq() {
        return (BigDecimal)ensureVariableManager().getVariableValue("BindPvtHdrSeq");
    }

    /**
     * Sets <code>value</code> for variable BindPvtHdrSeq.
     * @param value value to bind as BindPvtHdrSeq
     */
    public void setBindPvtHdrSeq(BigDecimal value) {
        ensureVariableManager().setVariableValue("BindPvtHdrSeq", value);
    }
}
