package com.imum.cpms.model.transactions.vo;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 13 16:06:00 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PVTIssuanceVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PVTNumber {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getPVTNumber();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setPVTNumber((String)value);
            }
        }
        ,
        PlateCategory {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getPlateCategory();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setPlateCategory((Integer)value);
            }
        }
        ,
        PlateType {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getPlateType();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setPlateType((String)value);
            }
        }
        ,
        PlateNumber {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getPlateNumber();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setPlateNumber((String)value);
            }
        }
        ,
        ContraventionCode {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getContraventionCode();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setContraventionCode((Integer)value);
            }
        }
        ,
        Sector {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getSector();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setSector((String)value);
            }
        }
        ,
        Country {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getCountry();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setCountry((String)value);
            }
        }
        ,
        City {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getCity();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setCity((String)value);
            }
        }
        ,
        VehicleGeoLatitude {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getVehicleGeoLatitude();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setVehicleGeoLatitude((String)value);
            }
        }
        ,
        VehicleGeoLongitude {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getVehicleGeoLongitude();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setVehicleGeoLongitude((String)value);
            }
        }
        ,
        VehicleMake {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getVehicleMake();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setVehicleMake((Integer)value);
            }
        }
        ,
        VehicleModel {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getVehicleModel();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setVehicleModel((String)value);
            }
        }
        ,
        VehicleColor {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getVehicleColor();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setVehicleColor((String)value);
            }
        }
        ,
        TariffType {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getTariffType();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setTariffType((String)value);
            }
        }
        ,
        PlateCountry {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getPlateCountry();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setPlateCountry((Integer)value);
            }
        }
        ,
        Zone {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getZone();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setZone((String)value);
            }
        }
        ,
        PVTIssuanceDate {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getPVTIssuanceDate();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setPVTIssuanceDate((Timestamp)value);
            }
        }
        ,
        ContraventionDescription {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getContraventionDescription();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setContraventionDescription((Integer)value);
            }
        }
        ,
        ContraCodeLOVVO1 {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getContraCodeLOVVO1();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PlateCategoryLOVVO1 {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getPlateCategoryLOVVO1();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PlateTypeLOVVO1 {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getPlateTypeLOVVO1();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        VehicleMakeLOVVO1 {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getVehicleMakeLOVVO1();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        VehicleModelLOVVO1 {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getVehicleModelLOVVO1();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SectorLovVO1 {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getSectorLovVO1();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        VehicleColourLOVVO1 {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getVehicleColourLOVVO1();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PVTTariffTypesLOVVO1 {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getPVTTariffTypesLOVVO1();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        VehiclePlateCountryLVO1 {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getVehiclePlateCountryLVO1();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ZoneLOVVO1 {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getZoneLOVVO1();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ContraDescLOVVO1 {
            public Object get(PVTIssuanceVORowImpl obj) {
                return obj.getContraDescLOVVO1();
            }

            public void put(PVTIssuanceVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PVTIssuanceVORowImpl object);

        public abstract void put(PVTIssuanceVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int PVTNUMBER = AttributesEnum.PVTNumber.index();
    public static final int PLATECATEGORY = AttributesEnum.PlateCategory.index();
    public static final int PLATETYPE = AttributesEnum.PlateType.index();
    public static final int PLATENUMBER = AttributesEnum.PlateNumber.index();
    public static final int CONTRAVENTIONCODE = AttributesEnum.ContraventionCode.index();
    public static final int SECTOR = AttributesEnum.Sector.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int CITY = AttributesEnum.City.index();
    public static final int VEHICLEGEOLATITUDE = AttributesEnum.VehicleGeoLatitude.index();
    public static final int VEHICLEGEOLONGITUDE = AttributesEnum.VehicleGeoLongitude.index();
    public static final int VEHICLEMAKE = AttributesEnum.VehicleMake.index();
    public static final int VEHICLEMODEL = AttributesEnum.VehicleModel.index();
    public static final int VEHICLECOLOR = AttributesEnum.VehicleColor.index();
    public static final int TARIFFTYPE = AttributesEnum.TariffType.index();
    public static final int PLATECOUNTRY = AttributesEnum.PlateCountry.index();
    public static final int ZONE = AttributesEnum.Zone.index();
    public static final int PVTISSUANCEDATE = AttributesEnum.PVTIssuanceDate.index();
    public static final int CONTRAVENTIONDESCRIPTION = AttributesEnum.ContraventionDescription.index();
    public static final int CONTRACODELOVVO1 = AttributesEnum.ContraCodeLOVVO1.index();
    public static final int PLATECATEGORYLOVVO1 = AttributesEnum.PlateCategoryLOVVO1.index();
    public static final int PLATETYPELOVVO1 = AttributesEnum.PlateTypeLOVVO1.index();
    public static final int VEHICLEMAKELOVVO1 = AttributesEnum.VehicleMakeLOVVO1.index();
    public static final int VEHICLEMODELLOVVO1 = AttributesEnum.VehicleModelLOVVO1.index();
    public static final int SECTORLOVVO1 = AttributesEnum.SectorLovVO1.index();
    public static final int VEHICLECOLOURLOVVO1 = AttributesEnum.VehicleColourLOVVO1.index();
    public static final int PVTTARIFFTYPESLOVVO1 = AttributesEnum.PVTTariffTypesLOVVO1.index();
    public static final int VEHICLEPLATECOUNTRYLVO1 = AttributesEnum.VehiclePlateCountryLVO1.index();
    public static final int ZONELOVVO1 = AttributesEnum.ZoneLOVVO1.index();
    public static final int CONTRADESCLOVVO1 = AttributesEnum.ContraDescLOVVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PVTIssuanceVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute PVTNumber.
     * @return the PVTNumber
     */
    public String getPVTNumber() {
        return (String) getAttributeInternal(PVTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PVTNumber.
     * @param value value to set the  PVTNumber
     */
    public void setPVTNumber(String value) {
        setAttributeInternal(PVTNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PlateCategory.
     * @return the PlateCategory
     */
    public Integer getPlateCategory() {
        return (Integer) getAttributeInternal(PLATECATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PlateCategory.
     * @param value value to set the  PlateCategory
     */
    public void setPlateCategory(Integer value) {
        setAttributeInternal(PLATECATEGORY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PlateType.
     * @return the PlateType
     */
    public String getPlateType() {
        return (String) getAttributeInternal(PLATETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PlateType.
     * @param value value to set the  PlateType
     */
    public void setPlateType(String value) {
        setAttributeInternal(PLATETYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PlateNumber.
     * @return the PlateNumber
     */
    public String getPlateNumber() {
        return (String) getAttributeInternal(PLATENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PlateNumber.
     * @param value value to set the  PlateNumber
     */
    public void setPlateNumber(String value) {
        setAttributeInternal(PLATENUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ContraventionCode.
     * @return the ContraventionCode
     */
    public Integer getContraventionCode() {
        return (Integer) getAttributeInternal(CONTRAVENTIONCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ContraventionCode.
     * @param value value to set the  ContraventionCode
     */
    public void setContraventionCode(Integer value) {
        setAttributeInternal(CONTRAVENTIONCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Sector.
     * @return the Sector
     */
    public String getSector() {
        return (String) getAttributeInternal(SECTOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Sector.
     * @param value value to set the  Sector
     */
    public void setSector(String value) {
        setAttributeInternal(SECTOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Country.
     * @return the Country
     */
    public String getCountry() {
        return (String) getAttributeInternal(COUNTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Country.
     * @param value value to set the  Country
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute City.
     * @return the City
     */
    public String getCity() {
        return (String) getAttributeInternal(CITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute City.
     * @param value value to set the  City
     */
    public void setCity(String value) {
        setAttributeInternal(CITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VehicleGeoLatitude.
     * @return the VehicleGeoLatitude
     */
    public String getVehicleGeoLatitude() {
        return (String) getAttributeInternal(VEHICLEGEOLATITUDE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VehicleGeoLatitude.
     * @param value value to set the  VehicleGeoLatitude
     */
    public void setVehicleGeoLatitude(String value) {
        setAttributeInternal(VEHICLEGEOLATITUDE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VehicleGeoLongitude.
     * @return the VehicleGeoLongitude
     */
    public String getVehicleGeoLongitude() {
        return (String) getAttributeInternal(VEHICLEGEOLONGITUDE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VehicleGeoLongitude.
     * @param value value to set the  VehicleGeoLongitude
     */
    public void setVehicleGeoLongitude(String value) {
        setAttributeInternal(VEHICLEGEOLONGITUDE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VehicleMake.
     * @return the VehicleMake
     */
    public Integer getVehicleMake() {
        return (Integer) getAttributeInternal(VEHICLEMAKE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VehicleMake.
     * @param value value to set the  VehicleMake
     */
    public void setVehicleMake(Integer value) {
        setAttributeInternal(VEHICLEMAKE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VehicleModel.
     * @return the VehicleModel
     */
    public String getVehicleModel() {
        return (String) getAttributeInternal(VEHICLEMODEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VehicleModel.
     * @param value value to set the  VehicleModel
     */
    public void setVehicleModel(String value) {
        setAttributeInternal(VEHICLEMODEL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VehicleColor.
     * @return the VehicleColor
     */
    public String getVehicleColor() {
        return (String) getAttributeInternal(VEHICLECOLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VehicleColor.
     * @param value value to set the  VehicleColor
     */
    public void setVehicleColor(String value) {
        setAttributeInternal(VEHICLECOLOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TariffType.
     * @return the TariffType
     */
    public String getTariffType() {
        return (String) getAttributeInternal(TARIFFTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TariffType.
     * @param value value to set the  TariffType
     */
    public void setTariffType(String value) {
        setAttributeInternal(TARIFFTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PlateCountry.
     * @return the PlateCountry
     */
    public Integer getPlateCountry() {
        return (Integer) getAttributeInternal(PLATECOUNTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PlateCountry.
     * @param value value to set the  PlateCountry
     */
    public void setPlateCountry(Integer value) {
        setAttributeInternal(PLATECOUNTRY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Zone.
     * @return the Zone
     */
    public String getZone() {
        return (String) getAttributeInternal(ZONE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Zone.
     * @param value value to set the  Zone
     */
    public void setZone(String value) {
        setAttributeInternal(ZONE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PVTIssuanceDate.
     * @return the PVTIssuanceDate
     */
    public Timestamp getPVTIssuanceDate() {
        return (Timestamp) getAttributeInternal(PVTISSUANCEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PVTIssuanceDate.
     * @param value value to set the  PVTIssuanceDate
     */
    public void setPVTIssuanceDate(Timestamp value) {
        setAttributeInternal(PVTISSUANCEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ContraventionDescription.
     * @return the ContraventionDescription
     */
    public Integer getContraventionDescription() {
        return (Integer) getAttributeInternal(CONTRAVENTIONDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ContraventionDescription.
     * @param value value to set the  ContraventionDescription
     */
    public void setContraventionDescription(Integer value) {
        setAttributeInternal(CONTRAVENTIONDESCRIPTION, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ContraCodeLOVVO1.
     */
    public RowSet getContraCodeLOVVO1() {
        return (RowSet)getAttributeInternal(CONTRACODELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PlateCategoryLOVVO1.
     */
    public RowSet getPlateCategoryLOVVO1() {
        return (RowSet)getAttributeInternal(PLATECATEGORYLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PlateTypeLOVVO1.
     */
    public RowSet getPlateTypeLOVVO1() {
        return (RowSet)getAttributeInternal(PLATETYPELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VehicleMakeLOVVO1.
     */
    public RowSet getVehicleMakeLOVVO1() {
        return (RowSet)getAttributeInternal(VEHICLEMAKELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VehicleModelLOVVO1.
     */
    public RowSet getVehicleModelLOVVO1() {
        return (RowSet)getAttributeInternal(VEHICLEMODELLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SectorLovVO1.
     */
    public RowSet getSectorLovVO1() {
        return (RowSet)getAttributeInternal(SECTORLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VehicleColourLOVVO1.
     */
    public RowSet getVehicleColourLOVVO1() {
        return (RowSet)getAttributeInternal(VEHICLECOLOURLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PVTTariffTypesLOVVO1.
     */
    public RowSet getPVTTariffTypesLOVVO1() {
        return (RowSet)getAttributeInternal(PVTTARIFFTYPESLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VehiclePlateCountryLVO1.
     */
    public RowSet getVehiclePlateCountryLVO1() {
        return (RowSet)getAttributeInternal(VEHICLEPLATECOUNTRYLVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ZoneLOVVO1.
     */
    public RowSet getZoneLOVVO1() {
        return (RowSet)getAttributeInternal(ZONELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ContraDescLOVVO1.
     */
    public RowSet getContraDescLOVVO1() {
        return (RowSet)getAttributeInternal(CONTRADESCLOVVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
