package com.imum.cpms.model.transactions.vo;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 05 10:09:08 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PVTTariffTypesLOVVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ValueCode {
            public Object get(PVTTariffTypesLOVVORowImpl obj) {
                return obj.getValueCode();
            }

            public void put(PVTTariffTypesLOVVORowImpl obj, Object value) {
                obj.setValueCode((String)value);
            }
        }
        ,
        ValueDesc {
            public Object get(PVTTariffTypesLOVVORowImpl obj) {
                return obj.getValueDesc();
            }

            public void put(PVTTariffTypesLOVVORowImpl obj, Object value) {
                obj.setValueDesc((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PVTTariffTypesLOVVORowImpl object);

        public abstract void put(PVTTariffTypesLOVVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int VALUECODE = AttributesEnum.ValueCode.index();
    public static final int VALUEDESC = AttributesEnum.ValueDesc.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PVTTariffTypesLOVVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ValueCode.
     * @return the ValueCode
     */
    public String getValueCode() {
        return (String) getAttributeInternal(VALUECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ValueCode.
     * @param value value to set the  ValueCode
     */
    public void setValueCode(String value) {
        setAttributeInternal(VALUECODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ValueDesc.
     * @return the ValueDesc
     */
    public String getValueDesc() {
        return (String) getAttributeInternal(VALUEDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ValueDesc.
     * @param value value to set the  ValueDesc
     */
    public void setValueDesc(String value) {
        setAttributeInternal(VALUEDESC, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
