package com.imum.cpms.model.masters.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 14 19:00:18 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GenMsgMstVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        MsgSeq {
            public Object get(GenMsgMstVORowImpl obj) {
                return obj.getMsgSeq();
            }

            public void put(GenMsgMstVORowImpl obj, Object value) {
                obj.setMsgSeq((BigDecimal)value);
            }
        }
        ,
        MsgDesc {
            public Object get(GenMsgMstVORowImpl obj) {
                return obj.getMsgDesc();
            }

            public void put(GenMsgMstVORowImpl obj, Object value) {
                obj.setMsgDesc((String)value);
            }
        }
        ,
        MsgType {
            public Object get(GenMsgMstVORowImpl obj) {
                return obj.getMsgType();
            }

            public void put(GenMsgMstVORowImpl obj, Object value) {
                obj.setMsgType((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(GenMsgMstVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(GenMsgMstVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(GenMsgMstVORowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(GenMsgMstVORowImpl obj, Object value) {
                obj.setCreatedDate((Timestamp)value);
            }
        }
        ,
        UpdatedBy {
            public Object get(GenMsgMstVORowImpl obj) {
                return obj.getUpdatedBy();
            }

            public void put(GenMsgMstVORowImpl obj, Object value) {
                obj.setUpdatedBy((String)value);
            }
        }
        ,
        UpdatedDate {
            public Object get(GenMsgMstVORowImpl obj) {
                return obj.getUpdatedDate();
            }

            public void put(GenMsgMstVORowImpl obj, Object value) {
                obj.setUpdatedDate((Timestamp)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(GenMsgMstVORowImpl object);

        public abstract void put(GenMsgMstVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int MSGSEQ = AttributesEnum.MsgSeq.index();
    public static final int MSGDESC = AttributesEnum.MsgDesc.index();
    public static final int MSGTYPE = AttributesEnum.MsgType.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GenMsgMstVORowImpl() {
    }


    /**
     * Gets the attribute value for the calculated attribute MsgSeq.
     * @return the MsgSeq
     */
    public BigDecimal getMsgSeq() {
        return (BigDecimal) getAttributeInternal(MSGSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MsgSeq.
     * @param value value to set the  MsgSeq
     */
    public void setMsgSeq(BigDecimal value) {
        setAttributeInternal(MSGSEQ, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MsgDesc.
     * @return the MsgDesc
     */
    public String getMsgDesc() {
        return (String) getAttributeInternal(MSGDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MsgDesc.
     * @param value value to set the  MsgDesc
     */
    public void setMsgDesc(String value) {
        setAttributeInternal(MSGDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MsgType.
     * @return the MsgType
     */
    public String getMsgType() {
        return (String) getAttributeInternal(MSGTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MsgType.
     * @param value value to set the  MsgType
     */
    public void setMsgType(String value) {
        setAttributeInternal(MSGTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy.
     * @param value value to set the  CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedDate.
     * @return the CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedDate.
     * @param value value to set the  CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }


    /**
     * Gets the attribute value for the calculated attribute UpdatedBy.
     * @return the UpdatedBy
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UpdatedBy.
     * @param value value to set the  UpdatedBy
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UpdatedDate.
     * @return the UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UpdatedDate.
     * @param value value to set the  UpdatedDate
     */
    public void setUpdatedDate(Timestamp value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
