package com.imum.cpms.model.masters.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 20 17:20:59 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HHDeviceMstUVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HHDeviceMstUVOImpl() {
    }
}
