package com.imum.cpms.model.masters.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 26 13:38:38 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class printBlackVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public printBlackVOImpl() {
    }
}
