package com.imum.cpms.model.masters.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;

import org.apache.myfaces.trinidad.model.UploadedFile;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 01 11:58:54 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PVTWRITEOFFDETAILSVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        WRITEOFFPVTDTLSeq {
            public Object get(PVTWRITEOFFDETAILSVORowImpl obj) {
                return obj.getWRITEOFFPVTDTLSeq();
            }

            public void put(PVTWRITEOFFDETAILSVORowImpl obj, Object value) {
                obj.setWRITEOFFPVTDTLSeq((BigDecimal)value);
            }
        }
        ,
        WRITEOFFHDRSeq {
            public Object get(PVTWRITEOFFDETAILSVORowImpl obj) {
                return obj.getWRITEOFFHDRSeq();
            }

            public void put(PVTWRITEOFFDETAILSVORowImpl obj, Object value) {
                obj.setWRITEOFFHDRSeq((BigDecimal)value);
            }
        }
        ,
        PVTHDRSEQ {
            public Object get(PVTWRITEOFFDETAILSVORowImpl obj) {
                return obj.getPVTHDRSEQ();
            }

            public void put(PVTWRITEOFFDETAILSVORowImpl obj, Object value) {
                obj.setPVTHDRSEQ((BigDecimal)value);
            }
        }
        ,
        PVTAMTPAYABLE {
            public Object get(PVTWRITEOFFDETAILSVORowImpl obj) {
                return obj.getPVTAMTPAYABLE();
            }

            public void put(PVTWRITEOFFDETAILSVORowImpl obj, Object value) {
                obj.setPVTAMTPAYABLE((BigDecimal)value);
            }
        }
        ,
        ReasonID {
            public Object get(PVTWRITEOFFDETAILSVORowImpl obj) {
                return obj.getReasonID();
            }

            public void put(PVTWRITEOFFDETAILSVORowImpl obj, Object value) {
                obj.setReasonID((Integer)value);
            }
        }
        ,
        RequesterRemarks {
            public Object get(PVTWRITEOFFDETAILSVORowImpl obj) {
                return obj.getRequesterRemarks();
            }

            public void put(PVTWRITEOFFDETAILSVORowImpl obj, Object value) {
                obj.setRequesterRemarks((String)value);
            }
        }
        ,
        Approvedflag {
            public Object get(PVTWRITEOFFDETAILSVORowImpl obj) {
                return obj.getApprovedflag();
            }

            public void put(PVTWRITEOFFDETAILSVORowImpl obj, Object value) {
                obj.setApprovedflag((String)value);
            }
        }
        ,
        ApproverRemarks {
            public Object get(PVTWRITEOFFDETAILSVORowImpl obj) {
                return obj.getApproverRemarks();
            }

            public void put(PVTWRITEOFFDETAILSVORowImpl obj, Object value) {
                obj.setApproverRemarks((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PVTWRITEOFFDETAILSVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PVTWRITEOFFDETAILSVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(PVTWRITEOFFDETAILSVORowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(PVTWRITEOFFDETAILSVORowImpl obj, Object value) {
                obj.setCreatedDate((Timestamp)value);
            }
        }
        ,
        Updatedby {
            public Object get(PVTWRITEOFFDETAILSVORowImpl obj) {
                return obj.getUpdatedby();
            }

            public void put(PVTWRITEOFFDETAILSVORowImpl obj, Object value) {
                obj.setUpdatedby((String)value);
            }
        }
        ,
        updateddate {
            public Object get(PVTWRITEOFFDETAILSVORowImpl obj) {
                return obj.getupdateddate();
            }

            public void put(PVTWRITEOFFDETAILSVORowImpl obj, Object value) {
                obj.setupdateddate((Timestamp)value);
            }
        }
        ,
        PvtNo {
            public Object get(PVTWRITEOFFDETAILSVORowImpl obj) {
                return obj.getPvtNo();
            }

            public void put(PVTWRITEOFFDETAILSVORowImpl obj, Object value) {
                obj.setPvtNo((String)value);
            }
        }
        ,
        FileUpload {
            public Object get(PVTWRITEOFFDETAILSVORowImpl obj) {
                return obj.getFileUpload();
            }

            public void put(PVTWRITEOFFDETAILSVORowImpl obj, Object value) {
                obj.setFileUpload((UploadedFile)value);
            }
        }
        ,
        pvtnumber {
            public Object get(PVTWRITEOFFDETAILSVORowImpl obj) {
                return obj.getpvtnumber();
            }

            public void put(PVTWRITEOFFDETAILSVORowImpl obj, Object value) {
                obj.setpvtnumber((String)value);
            }
        }
        ,
        filepath {
            public Object get(PVTWRITEOFFDETAILSVORowImpl obj) {
                return obj.getfilepath();
            }

            public void put(PVTWRITEOFFDETAILSVORowImpl obj, Object value) {
                obj.setfilepath((String)value);
            }
        }
        ,
        filename {
            public Object get(PVTWRITEOFFDETAILSVORowImpl obj) {
                return obj.getfilename();
            }

            public void put(PVTWRITEOFFDETAILSVORowImpl obj, Object value) {
                obj.setfilename((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PVTWRITEOFFDETAILSVORowImpl object);

        public abstract void put(PVTWRITEOFFDETAILSVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int WRITEOFFPVTDTLSEQ = AttributesEnum.WRITEOFFPVTDTLSeq.index();
    public static final int WRITEOFFHDRSEQ = AttributesEnum.WRITEOFFHDRSeq.index();
    public static final int PVTHDRSEQ = AttributesEnum.PVTHDRSEQ.index();
    public static final int PVTAMTPAYABLE = AttributesEnum.PVTAMTPAYABLE.index();
    public static final int REASONID = AttributesEnum.ReasonID.index();
    public static final int REQUESTERREMARKS = AttributesEnum.RequesterRemarks.index();
    public static final int APPROVEDFLAG = AttributesEnum.Approvedflag.index();
    public static final int APPROVERREMARKS = AttributesEnum.ApproverRemarks.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.Updatedby.index();
    public static final int UPDATEDDATE = AttributesEnum.updateddate.index();
    public static final int PVTNO = AttributesEnum.PvtNo.index();
    public static final int FILEUPLOAD = AttributesEnum.FileUpload.index();
    public static final int PVTNUMBER = AttributesEnum.pvtnumber.index();
    public static final int FILEPATH = AttributesEnum.filepath.index();
    public static final int FILENAME = AttributesEnum.filename.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PVTWRITEOFFDETAILSVORowImpl() {
    }

    /**
     * Gets PVTWRITEOFFDETAILSEO entity object.
     * @return the PVTWRITEOFFDETAILSEO
     */
    public EntityImpl getPVTWRITEOFFDETAILSEO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for WRITEOFF_PVT_DTL_Seq using the alias name WRITEOFFPVTDTLSeq.
     * @return the WRITEOFF_PVT_DTL_Seq
     */
    public BigDecimal getWRITEOFFPVTDTLSeq() {
        return (BigDecimal) getAttributeInternal(WRITEOFFPVTDTLSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for WRITEOFF_PVT_DTL_Seq using the alias name WRITEOFFPVTDTLSeq.
     * @param value value to set the WRITEOFF_PVT_DTL_Seq
     */
    public void setWRITEOFFPVTDTLSeq(BigDecimal value) {
        setAttributeInternal(WRITEOFFPVTDTLSEQ, value);
    }

    /**
     * Gets the attribute value for WRITEOFF_HDR_Seq using the alias name WRITEOFFHDRSeq.
     * @return the WRITEOFF_HDR_Seq
     */
    public BigDecimal getWRITEOFFHDRSeq() {
        return (BigDecimal) getAttributeInternal(WRITEOFFHDRSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for WRITEOFF_HDR_Seq using the alias name WRITEOFFHDRSeq.
     * @param value value to set the WRITEOFF_HDR_Seq
     */
    public void setWRITEOFFHDRSeq(BigDecimal value) {
        setAttributeInternal(WRITEOFFHDRSEQ, value);
    }

    /**
     * Gets the attribute value for PVT_HDR_SEQ using the alias name PVTHDRSEQ.
     * @return the PVT_HDR_SEQ
     */
    public BigDecimal getPVTHDRSEQ() {
        return (BigDecimal) getAttributeInternal(PVTHDRSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for PVT_HDR_SEQ using the alias name PVTHDRSEQ.
     * @param value value to set the PVT_HDR_SEQ
     */
    public void setPVTHDRSEQ(BigDecimal value) {
        setAttributeInternal(PVTHDRSEQ, value);
    }

    /**
     * Gets the attribute value for PVT_AMT_PAYABLE using the alias name PVTAMTPAYABLE.
     * @return the PVT_AMT_PAYABLE
     */
    public BigDecimal getPVTAMTPAYABLE() {
        return (BigDecimal) getAttributeInternal(PVTAMTPAYABLE);
    }

    /**
     * Sets <code>value</code> as attribute value for PVT_AMT_PAYABLE using the alias name PVTAMTPAYABLE.
     * @param value value to set the PVT_AMT_PAYABLE
     */
    public void setPVTAMTPAYABLE(BigDecimal value) {
        setAttributeInternal(PVTAMTPAYABLE, value);
    }

    /**
     * Gets the attribute value for Reason_ID using the alias name ReasonID.
     * @return the Reason_ID
     */
    public Integer getReasonID() {
        return (Integer) getAttributeInternal(REASONID);
    }

    /**
     * Sets <code>value</code> as attribute value for Reason_ID using the alias name ReasonID.
     * @param value value to set the Reason_ID
     */
    public void setReasonID(Integer value) {
        setAttributeInternal(REASONID, value);
    }

    /**
     * Gets the attribute value for Requester_Remarks using the alias name RequesterRemarks.
     * @return the Requester_Remarks
     */
    public String getRequesterRemarks() {
        return (String) getAttributeInternal(REQUESTERREMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for Requester_Remarks using the alias name RequesterRemarks.
     * @param value value to set the Requester_Remarks
     */
    public void setRequesterRemarks(String value) {
        setAttributeInternal(REQUESTERREMARKS, value);
    }

    /**
     * Gets the attribute value for Approved_flag using the alias name Approvedflag.
     * @return the Approved_flag
     */
    public String getApprovedflag() {
        return (String) getAttributeInternal(APPROVEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for Approved_flag using the alias name Approvedflag.
     * @param value value to set the Approved_flag
     */
    public void setApprovedflag(String value) {
        setAttributeInternal(APPROVEDFLAG, value);
    }

    /**
     * Gets the attribute value for Approver_Remarks using the alias name ApproverRemarks.
     * @return the Approver_Remarks
     */
    public String getApproverRemarks() {
        return (String) getAttributeInternal(APPROVERREMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for Approver_Remarks using the alias name ApproverRemarks.
     * @param value value to set the Approver_Remarks
     */
    public void setApproverRemarks(String value) {
        setAttributeInternal(APPROVERREMARKS, value);
    }

    /**
     * Gets the attribute value for Created_By using the alias name CreatedBy.
     * @return the Created_By
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for Created_By using the alias name CreatedBy.
     * @param value value to set the Created_By
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Created_Date using the alias name CreatedDate.
     * @return the Created_Date
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for Created_Date using the alias name CreatedDate.
     * @param value value to set the Created_Date
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Updated_by using the alias name Updatedby.
     * @return the Updated_by
     */
    public String getUpdatedby() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for Updated_by using the alias name Updatedby.
     * @param value value to set the Updated_by
     */
    public void setUpdatedby(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for updated_date using the alias name updateddate.
     * @return the updated_date
     */
    public Timestamp getupdateddate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for updated_date using the alias name updateddate.
     * @param value value to set the updated_date
     */
    public void setupdateddate(Timestamp value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for PvtNo using the alias name PvtNo.
     * @return the PvtNo
     */
    public String getPvtNo() {
        return (String) getAttributeInternal(PVTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for PvtNo using the alias name PvtNo.
     * @param value value to set the PvtNo
     */
    public void setPvtNo(String value) {
        setAttributeInternal(PVTNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FileUpload.
     * @return the FileUpload
     */
    public UploadedFile getFileUpload() {
      
        return (UploadedFile)getAttributeInternal(FILEUPLOAD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FileUpload.
     * @param value value to set the  FileUpload
     */
    public void setFileUpload(UploadedFile value) {
        setAttributeInternal(FILEUPLOAD, value);
    }


    /**
     * Gets the attribute value for the calculated attribute pvtnumber.
     * @return the pvtnumber
     */
    public String getpvtnumber() {
        return (String) getAttributeInternal(PVTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute pvtnumber.
     * @param value value to set the  pvtnumber
     */
    public void setpvtnumber(String value) {
        setAttributeInternal(PVTNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute filepath.
     * @return the filepath
     */
    public String getfilepath() {
        return (String) getAttributeInternal(FILEPATH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute filepath.
     * @param value value to set the  filepath
     */
    public void setfilepath(String value) {
        setAttributeInternal(FILEPATH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute filename.
     * @return the filename
     */
    public String getfilename() {
        return (String) getAttributeInternal(FILENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute filename.
     * @param value value to set the  filename
     */
    public void setfilename(String value) {
        setAttributeInternal(FILENAME, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
