package com.imum.cpms.model.masters.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 22 12:23:31 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PvtWriteOffProgVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PvtWriteOffProgVOImpl() {
    }
}
