package com.imum.cpms.model.masters.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 24 16:23:58 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ShiftMstUVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ShiftMstUVOImpl() {
    }
}
