package com.imum.cpms.model.masters.vo;

import java.sql.Date;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 20 18:44:36 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VehicleBlacklistMstVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public VehicleBlacklistMstVOImpl() {
    }
}
