package com.imum.cpms.model.masters.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 06 16:08:06 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ZoneMstLngVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ZoneMstLngVOImpl() {
    }
}
