package com.imum.cpms.model.masters.eo;

import java.math.BigDecimal;

import java.sql.Date;
import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 17 12:40:07 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ContraventionMstEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ContraCode {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getContraCode();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setContraCode((Integer)value);
            }
        }
        ,
        CountryCode {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getCountryCode();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setCountryCode((String)value);
            }
        }
        ,
        CodeNameEn {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getCodeNameEn();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setCodeNameEn((String)value);
            }
        }
        ,
        DescEn {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getDescEn();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setDescEn((String)value);
            }
        }
        ,
        LawVerNo {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getLawVerNo();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setLawVerNo((String)value);
            }
        }
        ,
        LawVerDt {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getLawVerDt();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setLawVerDt((Date)value);
            }
        }
        ,
        isPymtRelatedflag {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getisPymtRelatedflag();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setisPymtRelatedflag((String)value);
            }
        }
        ,
        isPermitRelated {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getisPermitRelated();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setisPermitRelated((String)value);
            }
        }
        ,
        BaseCostAmt {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getBaseCostAmt();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setBaseCostAmt((BigDecimal)value);
            }
        }
        ,
        WaitingPerd {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getWaitingPerd();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setWaitingPerd((Integer)value);
            }
        }
        ,
        Observreqflag {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getObservreqflag();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setObservreqflag((String)value);
            }
        }
        ,
        ClampReqflag {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getClampReqflag();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setClampReqflag((String)value);
            }
        }
        ,
        Stickerreqflag {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getStickerreqflag();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setStickerreqflag((String)value);
            }
        }
        ,
        RemovalReqflag {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getRemovalReqflag();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setRemovalReqflag((String)value);
            }
        }
        ,
        Warningreqflag {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getWarningreqflag();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setWarningreqflag((String)value);
            }
        }
        ,
        mParkcheckreqflag {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getmParkcheckreqflag();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setmParkcheckreqflag((String)value);
            }
        }
        ,
        PermitcheckReqflag {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getPermitcheckReqflag();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setPermitcheckReqflag((String)value);
            }
        }
        ,
        valonholidayflag {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getvalonholidayflag();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setvalonholidayflag((String)value);
            }
        }
        ,
        WhiteListFlag {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getWhiteListFlag();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setWhiteListFlag((String)value);
            }
        }
        ,
        ObservTime {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getObservTime();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setObservTime((BigDecimal)value);
            }
        }
        ,
        ValidFrom {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getValidFrom();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setValidFrom((Date)value);
            }
        }
        ,
        ValidTo {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getValidTo();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setValidTo((Date)value);
            }
        }
        ,
        ActiveFlag {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getActiveFlag();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setActiveFlag((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setCreatedDate((Timestamp)value);
            }
        }
        ,
        UpdatedBy {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getUpdatedBy();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setUpdatedBy((String)value);
            }
        }
        ,
        UpdatedDate {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getUpdatedDate();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setUpdatedDate((Timestamp)value);
            }
        }
        ,
        EnfreqPVTcnt {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getEnfreqPVTcnt();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setEnfreqPVTcnt((Integer)value);
            }
        }
        ,
        Enfreqdays {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getEnfreqdays();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setEnfreqdays((Integer)value);
            }
        }
        ,
        DiscountPCT {
            public Object get(ContraventionMstEOImpl obj) {
                return obj.getDiscountPCT();
            }

            public void put(ContraventionMstEOImpl obj, Object value) {
                obj.setDiscountPCT((BigDecimal)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(ContraventionMstEOImpl object);

        public abstract void put(ContraventionMstEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CONTRACODE = AttributesEnum.ContraCode.index();
    public static final int COUNTRYCODE = AttributesEnum.CountryCode.index();
    public static final int CODENAMEEN = AttributesEnum.CodeNameEn.index();
    public static final int DESCEN = AttributesEnum.DescEn.index();
    public static final int LAWVERNO = AttributesEnum.LawVerNo.index();
    public static final int LAWVERDT = AttributesEnum.LawVerDt.index();
    public static final int ISPYMTRELATEDFLAG = AttributesEnum.isPymtRelatedflag.index();
    public static final int ISPERMITRELATED = AttributesEnum.isPermitRelated.index();
    public static final int BASECOSTAMT = AttributesEnum.BaseCostAmt.index();
    public static final int WAITINGPERD = AttributesEnum.WaitingPerd.index();
    public static final int OBSERVREQFLAG = AttributesEnum.Observreqflag.index();
    public static final int CLAMPREQFLAG = AttributesEnum.ClampReqflag.index();
    public static final int STICKERREQFLAG = AttributesEnum.Stickerreqflag.index();
    public static final int REMOVALREQFLAG = AttributesEnum.RemovalReqflag.index();
    public static final int WARNINGREQFLAG = AttributesEnum.Warningreqflag.index();
    public static final int MPARKCHECKREQFLAG = AttributesEnum.mParkcheckreqflag.index();
    public static final int PERMITCHECKREQFLAG = AttributesEnum.PermitcheckReqflag.index();
    public static final int VALONHOLIDAYFLAG = AttributesEnum.valonholidayflag.index();
    public static final int WHITELISTFLAG = AttributesEnum.WhiteListFlag.index();
    public static final int OBSERVTIME = AttributesEnum.ObservTime.index();
    public static final int VALIDFROM = AttributesEnum.ValidFrom.index();
    public static final int VALIDTO = AttributesEnum.ValidTo.index();
    public static final int ACTIVEFLAG = AttributesEnum.ActiveFlag.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int ENFREQPVTCNT = AttributesEnum.EnfreqPVTcnt.index();
    public static final int ENFREQDAYS = AttributesEnum.Enfreqdays.index();
    public static final int DISCOUNTPCT = AttributesEnum.DiscountPCT.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ContraventionMstEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("com.imum.cpms.model.masters.eo.ContraventionMstEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for ContraCode, using the alias name ContraCode.
     * @return the ContraCode
     */
    public Integer getContraCode() {
        return (Integer)getAttributeInternal(CONTRACODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContraCode.
     * @param value value to set the ContraCode
     */
    public void setContraCode(Integer value) {
        setAttributeInternal(CONTRACODE, value);
    }

    /**
     * Gets the attribute value for CountryCode, using the alias name CountryCode.
     * @return the CountryCode
     */
    public String getCountryCode() {
        return (String)getAttributeInternal(COUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CountryCode.
     * @param value value to set the CountryCode
     */
    public void setCountryCode(String value) {
        setAttributeInternal(COUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for CodeNameEn, using the alias name CodeNameEn.
     * @return the CodeNameEn
     */
    public String getCodeNameEn() {
        return (String)getAttributeInternal(CODENAMEEN);
    }

    /**
     * Sets <code>value</code> as the attribute value for CodeNameEn.
     * @param value value to set the CodeNameEn
     */
    public void setCodeNameEn(String value) {
        setAttributeInternal(CODENAMEEN, value);
    }

    /**
     * Gets the attribute value for DescEn, using the alias name DescEn.
     * @return the DescEn
     */
    public String getDescEn() {
        return (String)getAttributeInternal(DESCEN);
    }

    /**
     * Sets <code>value</code> as the attribute value for DescEn.
     * @param value value to set the DescEn
     */
    public void setDescEn(String value) {
        setAttributeInternal(DESCEN, value);
    }

    /**
     * Gets the attribute value for LawVerNo, using the alias name LawVerNo.
     * @return the LawVerNo
     */
    public String getLawVerNo() {
        return (String)getAttributeInternal(LAWVERNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for LawVerNo.
     * @param value value to set the LawVerNo
     */
    public void setLawVerNo(String value) {
        setAttributeInternal(LAWVERNO, value);
    }

    /**
     * Gets the attribute value for LawVerDt, using the alias name LawVerDt.
     * @return the LawVerDt
     */
    public Date getLawVerDt() {
        return (Date)getAttributeInternal(LAWVERDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for LawVerDt.
     * @param value value to set the LawVerDt
     */
    public void setLawVerDt(Date value) {
        setAttributeInternal(LAWVERDT, value);
    }

    /**
     * Gets the attribute value for isPymtRelatedflag, using the alias name isPymtRelatedflag.
     * @return the isPymtRelatedflag
     */
    public String getisPymtRelatedflag() {
        return (String)getAttributeInternal(ISPYMTRELATEDFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for isPymtRelatedflag.
     * @param value value to set the isPymtRelatedflag
     */
    public void setisPymtRelatedflag(String value) {
        setAttributeInternal(ISPYMTRELATEDFLAG, value);
    }

    /**
     * Gets the attribute value for isPermitRelated, using the alias name isPermitRelated.
     * @return the isPermitRelated
     */
    public String getisPermitRelated() {
        return (String)getAttributeInternal(ISPERMITRELATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for isPermitRelated.
     * @param value value to set the isPermitRelated
     */
    public void setisPermitRelated(String value) {
        setAttributeInternal(ISPERMITRELATED, value);
    }

    /**
     * Gets the attribute value for BaseCostAmt, using the alias name BaseCostAmt.
     * @return the BaseCostAmt
     */
    public BigDecimal getBaseCostAmt() {
        return (BigDecimal)getAttributeInternal(BASECOSTAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for BaseCostAmt.
     * @param value value to set the BaseCostAmt
     */
    public void setBaseCostAmt(BigDecimal value) {
        setAttributeInternal(BASECOSTAMT, value);
    }

    /**
     * Gets the attribute value for WaitingPerd, using the alias name WaitingPerd.
     * @return the WaitingPerd
     */
    public Integer getWaitingPerd() {
        return (Integer)getAttributeInternal(WAITINGPERD);
    }

    /**
     * Sets <code>value</code> as the attribute value for WaitingPerd.
     * @param value value to set the WaitingPerd
     */
    public void setWaitingPerd(Integer value) {
        setAttributeInternal(WAITINGPERD, value);
    }

    /**
     * Gets the attribute value for Observreqflag, using the alias name Observreqflag.
     * @return the Observreqflag
     */
    public String getObservreqflag() {
        return (String)getAttributeInternal(OBSERVREQFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for Observreqflag.
     * @param value value to set the Observreqflag
     */
    public void setObservreqflag(String value) {
        setAttributeInternal(OBSERVREQFLAG, value);
    }

    /**
     * Gets the attribute value for ClampReqflag, using the alias name ClampReqflag.
     * @return the ClampReqflag
     */
    public String getClampReqflag() {
        return (String)getAttributeInternal(CLAMPREQFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ClampReqflag.
     * @param value value to set the ClampReqflag
     */
    public void setClampReqflag(String value) {
        setAttributeInternal(CLAMPREQFLAG, value);
    }

    /**
     * Gets the attribute value for Stickerreqflag, using the alias name Stickerreqflag.
     * @return the Stickerreqflag
     */
    public String getStickerreqflag() {
        return (String)getAttributeInternal(STICKERREQFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for Stickerreqflag.
     * @param value value to set the Stickerreqflag
     */
    public void setStickerreqflag(String value) {
        setAttributeInternal(STICKERREQFLAG, value);
    }

    /**
     * Gets the attribute value for RemovalReqflag, using the alias name RemovalReqflag.
     * @return the RemovalReqflag
     */
    public String getRemovalReqflag() {
        return (String)getAttributeInternal(REMOVALREQFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for RemovalReqflag.
     * @param value value to set the RemovalReqflag
     */
    public void setRemovalReqflag(String value) {
        setAttributeInternal(REMOVALREQFLAG, value);
    }

    /**
     * Gets the attribute value for Warningreqflag, using the alias name Warningreqflag.
     * @return the Warningreqflag
     */
    public String getWarningreqflag() {
        return (String)getAttributeInternal(WARNINGREQFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for Warningreqflag.
     * @param value value to set the Warningreqflag
     */
    public void setWarningreqflag(String value) {
        setAttributeInternal(WARNINGREQFLAG, value);
    }

    /**
     * Gets the attribute value for mParkcheckreqflag, using the alias name mParkcheckreqflag.
     * @return the mParkcheckreqflag
     */
    public String getmParkcheckreqflag() {
        return (String)getAttributeInternal(MPARKCHECKREQFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for mParkcheckreqflag.
     * @param value value to set the mParkcheckreqflag
     */
    public void setmParkcheckreqflag(String value) {
        setAttributeInternal(MPARKCHECKREQFLAG, value);
    }


    /**
     * Gets the attribute value for PermitcheckReqflag, using the alias name PermitcheckReqflag.
     * @return the PermitcheckReqflag
     */
    public String getPermitcheckReqflag() {
        return (String)getAttributeInternal(PERMITCHECKREQFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for PermitcheckReqflag.
     * @param value value to set the PermitcheckReqflag
     */
    public void setPermitcheckReqflag(String value) {
        setAttributeInternal(PERMITCHECKREQFLAG, value);
    }

    /**
     * Gets the attribute value for valonholidayflag, using the alias name valonholidayflag.
     * @return the valonholidayflag
     */
    public String getvalonholidayflag() {
        return (String)getAttributeInternal(VALONHOLIDAYFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for valonholidayflag.
     * @param value value to set the valonholidayflag
     */
    public void setvalonholidayflag(String value) {
        setAttributeInternal(VALONHOLIDAYFLAG, value);
    }

    /**
     * Gets the attribute value for WhiteListFlag, using the alias name WhiteListFlag.
     * @return the WhiteListFlag
     */
    public String getWhiteListFlag() {
        return (String)getAttributeInternal(WHITELISTFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for WhiteListFlag.
     * @param value value to set the WhiteListFlag
     */
    public void setWhiteListFlag(String value) {
        setAttributeInternal(WHITELISTFLAG, value);
    }

    /**
     * Gets the attribute value for ObservTime, using the alias name ObservTime.
     * @return the ObservTime
     */
    public BigDecimal getObservTime() {
        return (BigDecimal)getAttributeInternal(OBSERVTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ObservTime.
     * @param value value to set the ObservTime
     */
    public void setObservTime(BigDecimal value) {
        setAttributeInternal(OBSERVTIME, value);
    }

    /**
     * Gets the attribute value for ValidFrom, using the alias name ValidFrom.
     * @return the ValidFrom
     */
    public Date getValidFrom() {
        return (Date)getAttributeInternal(VALIDFROM);
    }

    /**
     * Sets <code>value</code> as the attribute value for ValidFrom.
     * @param value value to set the ValidFrom
     */
    public void setValidFrom(Date value) {
        setAttributeInternal(VALIDFROM, value);
    }

    /**
     * Gets the attribute value for ValidTo, using the alias name ValidTo.
     * @return the ValidTo
     */
    public Date getValidTo() {
        return (Date)getAttributeInternal(VALIDTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ValidTo.
     * @param value value to set the ValidTo
     */
    public void setValidTo(Date value) {
        setAttributeInternal(VALIDTO, value);
    }

    /**
     * Gets the attribute value for ActiveFlag, using the alias name ActiveFlag.
     * @return the ActiveFlag
     */
    public String getActiveFlag() {
        return (String)getAttributeInternal(ACTIVEFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActiveFlag.
     * @param value value to set the ActiveFlag
     */
    public void setActiveFlag(String value) {
        setAttributeInternal(ACTIVEFLAG, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp)getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the UpdatedBy
     */
    public String getUpdatedBy() {
        return (String)getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp)getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedDate.
     * @param value value to set the UpdatedDate
     */
    public void setUpdatedDate(Timestamp value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for EnfreqPVTcnt, using the alias name EnfreqPVTcnt.
     * @return the EnfreqPVTcnt
     */
    public Integer getEnfreqPVTcnt() {
        return (Integer)getAttributeInternal(ENFREQPVTCNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for EnfreqPVTcnt.
     * @param value value to set the EnfreqPVTcnt
     */
    public void setEnfreqPVTcnt(Integer value) {
        setAttributeInternal(ENFREQPVTCNT, value);
    }

    /**
     * Gets the attribute value for Enfreqdays, using the alias name Enfreqdays.
     * @return the Enfreqdays
     */
    public Integer getEnfreqdays() {
        return (Integer)getAttributeInternal(ENFREQDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Enfreqdays.
     * @param value value to set the Enfreqdays
     */
    public void setEnfreqdays(Integer value) {
        setAttributeInternal(ENFREQDAYS, value);
    }


    /**
     * Gets the attribute value for DiscountPCT, using the alias name DiscountPCT.
     * @return the DiscountPCT
     */
    public BigDecimal getDiscountPCT() {
        return (BigDecimal)getAttributeInternal(DISCOUNTPCT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DiscountPCT.
     * @param value value to set the DiscountPCT
     */
    public void setDiscountPCT(BigDecimal value) {
        setAttributeInternal(DISCOUNTPCT, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param contraCode key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer contraCode) {
        return new Key(new Object[]{contraCode});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
