package com.imum.cpms.model.staffdeploy.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 07 16:04:54 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GenLocationLOVVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public GenLocationLOVVOImpl() {
    }
}
