package com.imum.ws.CardInactive;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://192.168.200.112:8001/soa-infra/services/default/CardInactiveApprovalBPM/CardInactivepprovalBPMProcess.service?WSDL",
  targetNamespace="http://xmlns.oracle.com/bpmn/bpmnProcess/CardInactivepprovalBPMProcess",
  name="CardInactivepprovalBPMProcessPortType")
@XmlSeeAlso(
  { ObjectFactory.class })
public interface CardInactivepprovalBPMProcessPortType
{
  @WebMethod(action="start")
  @Action(input="start")
  @RequestWrapper(localName="start", targetNamespace="http://xmlns.oracle.com/bpmn/bpmnProcess/CardInactivepprovalBPMProcess",
    className="com.imum.ws.CardInactive.Start")
  @Oneway
  public void start(@WebParam(targetNamespace="", name="cardInactive_seq")
    long cardInactiveSeq);
}
